

import { Categoria, Ginocchio, Attacco } from './types';

export const CATEGORY_COLORS: Record<Categoria, string> = {
  [Categoria.Bilanciato]: '#CDBB00',
  [Categoria.Fruttato]: '#ca1828',
  [Categoria.Erbaceo]: '#45AD63',
  [Categoria.Speziato]: '#0072BB',
};

export const CATEGORIES_ORDER: Categoria[] = [
  Categoria.Bilanciato,
  Categoria.Erbaceo,
  Categoria.Fruttato,
  Categoria.Speziato,
];

export const APP_TITLE = "GINDEX";

// Raw data for Ginocchi PV and Attacks
const RAW_GINOCCHI_DETAILS_TEXT = `
1	Punturirma	A	19	Pera di gin	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Bocce stordenti	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Intubazione pandemica	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Pasto ospedaliero	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Fascino della divisa	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ago nel midollo	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
2	Roboshop	B	18	Carrello di agrumi	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Penetrazione robotica	Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Assistenza virtuale	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Spesa a domicilio	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Vibromassaggiatore assassino	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Upgrade terminale	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.
3	Robinario	C	17	Doppio vomito	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Doppia scorreggia	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Autoerotismo poliamoroso	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Depressione collettiva	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Sbronza anaerobica	Danno: 3	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Gin al napalm	Danno: 4	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
4	Prepezio	D	14	Entrata forzata	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Scappellamento	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Bacioanale	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Tunneling sgradevole	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Cocknado	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Sodomia mineraria	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.
5	Gorettore	A	22	Rissa da Pub	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Ubriachezza frustrata	Danno: 3	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Ansia da partita IVA	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Fatturazione elettronica	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Resa dei conti	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Contusione letale	Danno: Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.
6	Guerraniglio	B	19	Ti sparo	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Mi sparo su un piede	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Riproduzione come conigli	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Carota detonante	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Incursione lagomorfa	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Esercitazione suicida	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
7	Tossicozza	C	18	Vulvochiusura bivalvica	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Perla nucleare	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Orefizio imperscrutabile	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Scorza tossica	Danno: 3	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Bivalve tossicodipendente	Danno: 3	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Marea nera endovenosa	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.
8	Scarabarman	D	15	Cocktail ai metalli pesanti	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Tripla shakerata	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Alcolismo distruttivo	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Happy Hour tossico	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Vermouth radioattivo	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Shackeramento letale	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.
9	Sborniadrago	A	19	Respiro del drago ubriaco	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Pissing autoinflitto	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Bava alcolemica	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Etilofiamma ancestrale	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Volo barcollante	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Incendio digestivo	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.
10	Tigrallo	B	19	Ruggito neoborbonico	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Morso neomelodico	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Chiagn e fott	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Fasti neobarocchi	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Digestione della bufala	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Confusione genetica	Danno: Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.
11	Roboraffa	C	16	Ossiconi Assassini	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Allungamento	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Morso erbivoro metallico	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Coccolone letale	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Bioingegneria pansessuale	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ricordo della savana	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.
12	Florona	C	16	Seduzione furry	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Bouquet di dildi	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Aroma inebriante	Danno: 5	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Leccata di gatta	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Coccolone peloso	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Dildo a sorpresa	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
13	Ran-occhio	D	15	Sputo del Gange	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Finocchiata	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Spruzzo di girini	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Sovrappopolazione	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Germoglio letale	Danno: 4	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Aromaterapia estrema	Danno: Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.
14	Arundizilla	A	20	Amore non corrisposto	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Conquista vegetale	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Nuggets vegani	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Lancia di sedano	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Crociata crudista	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Zuppa di umani	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.
15	Gelsosauro	B	17	Tirannomorso	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Pissing dalla pelle	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Odio aromatico preistorico	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Urina corrosiva	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fioritura esplosiva	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Petalo terminale	Danno: Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)
16	Lavandasma	C	17	Furto dell'anima	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Incubo alla lavanda	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Abbraccio di marsiglia	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Profumo letale	Danno: 2	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Essenza di morte	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Incubo profumato	Danno: Danno: 3	Spogliato - Non può difendersi al prossimo attacco.
17	Salviananda	D	17	Colpo femminista	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Colpo ecologista	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Incatenata all'opera d'arte	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Eco-terrorismo letale	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Liana strangolatrice	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Ascia verde sangue	Danno: Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.
18	Koajhonny	A	21	Bicipite balsamico	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Caduta dall'albero	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Potenza officinale	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Abbraccio asfissiante	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Marsupio esplosivo	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fisting marsupiale	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.
19	Rosiro	B	18	Sguardo irresistibile	Danno: 3	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Petali di rosa	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Orgoglio Queer	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Parata orgiastica	Danno: 2	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Corteo bestiale	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Fluido ipnotico	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.
20	Rosella	C	16	Shock pettoruto	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Rose transfemministe	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Penetrazione a sorpresa	Danno: 3	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Orgia infernale	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Stregoneria sodomita	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Quartetto letale (seno e gonadi)	Danno: Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.
21	Cybermint	D	14	Sensualità cibernetica	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Vagina con firewall	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Turbine mentolato	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Upload estremo	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Mentolo assassino	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Sistema di difesa attiva	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.
22	Rosmaruma	B	17	Saggezza aromatica	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Scorza impenetrabile	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Stoico condimento	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Letame sepolcrale	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Defecazione distruttiva	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Radice strangolatrice	Danno: Danno: 3	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)
23	Cetriolana ottava	C	16	Regalità falliforme	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Cetrioli birichini	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Sudditanza ortaggifera	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Incastro imperiale	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Punizione alla plebaglia	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Entra tutto signori	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.
24	Rosmanguilla	D	16	Pesce condito	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Amore interraziale	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Secrezioni anguillose sguillose	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Scivolata mortale	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Scarica elettrica	Danno: 3	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Morso viscido ma saporito	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.
25	Banona	A	17	Ti plano nel culo con una banana	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Banana split	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Volo Chiquita	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Doppio selfie letale	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Like assassini	Danno: 1	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Followers della morte	Danno: Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)
26	Tony Ansiolitico	B	16	Amore per le droghe	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Trip in the Bag	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Cristalloni volanti	Danno: 5	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Euro messi male	Danno: 5	Spogliato - Non può difendersi al prossimo attacco.	Tachicardia demoniaca	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Morte da after	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
27	Cervarancio	C	17	Cazzo agrumato gargantuesco	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Buccia repellente	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Cervopotenza ancestrale	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Esplosione di polpa	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Spremuta di muscoli	Danno: 3	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Corna cazzutissime del dio aranciato	Danno: Danno: 3	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)
28	Merlotta	D	14	Aratro voltaorecchio	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Cultivar franche di piede	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Lieviti indigeni	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fermentazione estrema	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Vinificazione crudele	Danno: 5	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Tannino letale	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.
29	Corvananas	A	18	Seme profumato	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	6Danno: 19 senza l'one	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Wrestlermania Danno: 18	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Scatto tropicale	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Becco afrodisiaco	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Volo acrobatico	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
30	Fiammaciofo	B	18	Incubo fiammeggiante	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Odore di carciofo	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Multimasturbazione poli bukkakika	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fiamma tossica	Danno: 2	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Cuore di piombo	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Carbonizzazione finale	Danno: Danno: 1	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)
31	Rosa cagnolina	C	15	Marmellata di rosa canina	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Gender gap vegetale	Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Spine dell'amore sopra ogni cosa	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Allattamento tossico	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Morso avvelenato	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Latrato fatale	Danno: Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.
32	Pipimone	D	17	Aspra trascendenza	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Diaconato agrumato	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Ultrasuoni sacri	Danno: 4	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Minzione divina	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Getto purificatore	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Lavaggio estremo	Danno: Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.
33	Eremillo	A	19	Saggezza antica	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra. - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Un sacco di bacche	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	GDILF	Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	vita senza defecazione	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Antiossidante pazzesco	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Respiro ai mirtilli	Danno: Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.
34	Mangodillo	B	19	Jackpot	Danno: 3	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Una rondine andata via	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Ludopatia tropicale	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Scaglie da poker	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	All in fruttato	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Slot machine vertebrale	Danno: Danno: 2	Spogliato - Non può difendersi al prossimo attacco.
35	Lampolpo	C	18	Amore tentacolare	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ventose succhiatrici	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	o' Purp 'mbuttunat	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Ventosa soffocante	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Stretta mortale	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Calamaro stritolante	Danno: Danno: 2	Spogliato - Non può difendersi al prossimo attacco.
36	Delfimaru	D	17	Shuriken delfinici	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Sfintere ninja	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Voglio diventare Hokage	Danno: 2	Spogliato - Non può difendersi al prossimo attacco.	Onda assassina	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Lama marina	Danno: 4	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Nuotata kamikaze	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
37	Pignacano	A	18	Pinoli volanti	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Piume ignifughe	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Beccata di tristezza	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Seme velenoso	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Radice esplosiva	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Partenogenesi letale	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.
38	Pompecora	B	19	Aspra lana	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Sbucciare un esperidio	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Pom-pecorina	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Tosatura selvaggia	Danno: 2	Spogliato - Non può difendersi al prossimo attacco.	Rutto alcolico	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Zoccolo frantumatore	Danno: Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.
39	Winenot?	C	16	Sensualità furry	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Molti bicchieri di vino	Danno: 4	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Potenza radical chic	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Sorso letale	Danno: 3	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Sciabolata da gigolò	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Sbronza assassina	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
40	Callista	D	17	Necrofilia indotta	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ritorno dalla morte	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Putrefazione avanzata	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Cripto-overdose	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Borsa dritta al cimitero	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Morte NFT	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
41	Cannellorca	A	20	Affondanavi speziato	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Colpo idrofobo	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Grasso che cola	Danno: 2	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Tsunami alla cannella	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Ondata Macellatrice	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Fauci del giovedì	Danno: Danno: 1	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)
42	Anicinzia	B	18	Magia del Rasentin	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Follia dei ghiacci	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Arcanomanzia balsamica	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Ghiacciolo letale	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Infusione stregata	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Sbornia dolce	Danno: Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.
43	Fumello	C	17	Ganja power	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Cartina aromatica	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Stonamento	Danno: 3	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Bomba spliff	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Teoria del complotto	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Abduction aliena	Danno: Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.
44	Peperonbro	D	18	Malavita piccante	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Thug life	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Battaglia rap	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Street food killer	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Salsa esplosiva	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Capo gang aromatica	Danno: Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.
45	Blobaffè	A	19	Caffè sospeso	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Scordammc' o passat	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Tazzulella	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Espresso bollente	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Crema di fango	Danno: 2	Bloccca movimento	Tazzina mortale	Danno: Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)
46	Speziatopo	B	19	Spaccio di pepi	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	La rogna	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Orecchie da mercante	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Dose letale	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Formaggio drogato	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Topo kamikaze	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
47	Borghesiglio	C	18	Opulenza polentona	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Fascino alla moda	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Riproduzione come conigli	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Scacco matto massonico	Danno: 4	Blocca movimento - L'avversario non può muoversi al prossimo turno.	Bonifico istantaneo	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Martiny dry a Danno: 2Danno: 2€	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
48	Teabear	D	18	Zanna della teina dopante	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Tazza di the sanguinoso	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Ruggito dell'orso mangiabambini	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Porcellana avvelenata	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Filtrino strangolatore	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Infusione letale	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.
49	Tzatzikeye	A	20	Dressing assassino	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Muffa cetriolifera	Danno: 4	Tossicodipendenza - Il bersaglio è costretto ad attaccare lo stesso Ginocchio del turno precedente. Se non può, non si attacca.	Insalata greca	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Diarrea esplosiva	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Emorroidi galattiche	Danno: 2	Paralisi totale -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile) -Il Ginocchio non può muoversi né attaccare al prossimo turno (non cumulabile)	Vinaigrette mortale	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco
50	Fuega	B	18	Piccantezza in straming	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Orgoglio contadino	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Danno: 10000000000 Punti scorville	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Dildo di fuoco	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Tortura piccante	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Onlyfans letale	Danno: Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.
`;

interface ParsedGinocchioDetails {
  id: number;
  pvIniziali: number;
  attacchi: Attacco[];
}

function parseRawGinocchioTextData(rawData: string): Map<number, ParsedGinocchioDetails> {
  const map = new Map<number, ParsedGinocchioDetails>();
  const lines = rawData.trim().split('\n');

  for (const line of lines) {
    const parts = line.split('\t');
    if (parts.length < 4 + 6 * 3) { // 4 base fields + 6 attacks * 3 fields each
      console.warn("Skipping malformed line:", line);
      continue;
    }

    const id = parseInt(parts[0], 10);
    // parts[1] is name in raw data, parts[2] is letter - we use names from structured data below
    const pvIniziali = parseInt(parts[3], 10);
    const attacchi: Attacco[] = [];

    for (let i = 0; i < 6; i++) {
      const attackName = parts[4 + (i * 3)];
      let attackDamage = parts[4 + (i * 3) + 1];
      const attackEffect = parts[4 + (i * 3) + 2];

      // Clean up "Danno:" prefix
      if (attackDamage.startsWith("Danno: Danno: ")) {
        attackDamage = attackDamage.substring("Danno: Danno: ".length);
      } else if (attackDamage.startsWith("Danno: ")) {
        attackDamage = attackDamage.substring("Danno: ".length);
      }
      
      attacchi.push({
        dado: i + 1,
        nome: attackName,
        danno: attackDamage.trim(),
        effetto: attackEffect,
      });
    }
    map.set(id, { id, pvIniziali, attacchi });
  }
  return map;
}

const parsedGinocchiDetailsMap = parseRawGinocchioTextData(RAW_GINOCCHI_DETAILS_TEXT);


// Ginocchi Data Base (Names and Categories)
const bilanciatiData = [
  { id: 1, nome: "Punturirma" }, { id: 2, nome: "Roboshop" }, { id: 3, nome: "Robinario" },
  { id: 4, nome: "Prepezio" }, { id: 5, nome: "Gorettore" }, { id: 6, nome: "Guerraniglio" },
  { id: 7, nome: "Tossicozza" }, { id: 8, nome: "Scarabarman" }, { id: 9, nome: "Sborniadrago" },
  { id: 10, nome: "Tigrallo" }, { id: 11, nome: "Roboraffa" }
].map(g => ({ ...g, categoria: Categoria.Bilanciato, colore: CATEGORY_COLORS[Categoria.Bilanciato]}));

const erbaceiData = [
  { id: 12, nome: "Florona" }, { id: 13, nome: "Ran-occhio" }, { id: 14, nome: "Arundizilla" },
  { id: 15, nome: "Gelsosauro" }, { id: 16, nome: "Lavandasma" }, { id: 17, nome: "Salviananda" },
  { id: 18, nome: "Koajhonny" }, { id: 19, nome: "Rosiro" }, { id: 20, nome: "Rosella" },
  { id: 21, nome: "Cybermint" }, { id: 22, nome: "Rosmaruma" }, { id: 23, nome: "Cetriol​ana ottava" },
  { id: 24, nome: "Rosmanguilla" }
].map(g => ({ ...g, categoria: Categoria.Erbaceo, colore: CATEGORY_COLORS[Categoria.Erbaceo]}));

const fruttatiData = [
  { id: 25, nome: "Banona" }, { id: 26, nome: "Tony Ansiolitico" }, { id: 27, nome: "Cervarancio" }, // Corrected name for ID 26
  { id: 28, nome: "Merlotta" }, { id: 29, nome: "Corvananas" }, { id: 30, nome: "Fiammaciofo" },
  { id: 31, nome: "Rosa cagnolina" }, { id: 32, nome: "Pipimone" }, { id: 33, nome: "Eremillo" },
  { id: 34, nome: "Mangodillo" }, { id: 35, nome: "Lampolpo" }, { id: 36, nome: "Delfimaru" },
  { id: 37, nome: "Pignacano" }, { id: 38, nome: "Pompecora" }, { id: 39, nome: "Winenot?" }
].map(g => ({ ...g, categoria: Categoria.Fruttato, colore: CATEGORY_COLORS[Categoria.Fruttato]}));

const speziatiData = [
  { id: 40, nome: "Callista" }, { id: 41, nome: "Cannellorca" }, { id: 42, nome: "Anicinzia" },
  { id: 43, nome: "Fumello" }, { id: 44, nome: "Peperonbro" }, { id: 45, nome: "Blobaffè" },
  { id: 46, nome: "Speziatopo" }, { id: 47, nome: "Borghesiglio" }, { id: 48, nome: "Teabear" },
  { id: 49, nome: "Tzatzikeye" }, { id: 50, nome: "Fuega" }
].map(g => ({ ...g, categoria: Categoria.Speziato, colore: CATEGORY_COLORS[Categoria.Speziato]}));

export const ALL_GINOCCHI: Ginocchio[] = [
  ...bilanciatiData, ...erbaceiData, ...fruttatiData, ...speziatiData
].map(baseGinocchio => {
  const details = parsedGinocchiDetailsMap.get(baseGinocchio.id);
  if (!details) {
    console.warn(`Missing PV/Attack details for Ginocchio ID ${baseGinocchio.id} (${baseGinocchio.nome}). Using defaults.`);
    return {
      ...baseGinocchio,
      immagine: `/images/ginocchi/${baseGinocchio.id}.png`, // Default to expected path even if details missing
      attacchi: [], 
      pvIniziali: 40, 
    };
  }
  // Corrected the name for Ginocchio with ID 26 from "Tony Ephedrina" to "Tony Ansiolitico" as per raw data
  const correctedName = baseGinocchio.id === 26 ? "Tony Ansiolitico" : baseGinocchio.nome;

  return {
    ...baseGinocchio, 
    nome: correctedName,
    immagine: `/images/ginocchi/${baseGinocchio.id}.png`, 
    attacchi: details.attacchi,
    pvIniziali: details.pvIniziali,
  };
});
