
import { Categoria, Ginocchio, Attacco } from './types';

export const CATEGORY_COLORS: Record<Categoria, string> = {
  [Categoria.Bilanciato]: '#CDBB00',
  [Categoria.Fruttato]: '#ca1828',
  [Categoria.Erbaceo]: '#45AD63',
  [Categoria.Speziato]: '#0072BB',
};

export const CATEGORIES_ORDER: Categoria[] = [
  Categoria.Bilanciato,
  Categoria.Erbaceo,
  Categoria.Fruttato,
  Categoria.Speziato,
];

export const APP_TITLE = "GINDEX";

export const PV_QUOTES: Record<number, string> = {
  22: "Nessuno ti ha ancora picchiato. È solo questione di tempo.", // Added for Gorettore
  21: "Nessuno ti ha ancora picchiato. È solo questione di tempo.",
  20: "Troppa energia. Sei già insopportabile.",
  19: "Troppo sano per essere simpatico.",
  18: "Sei come le emorroidi: difficile da eliminare.",
  17: "Sei ancora in piedi. Come un coglione.",
  16: "Sei lucido. Ed è un problema.",
  15: "Ti senti invincibile ma sei solo patetico.",
  14: "Hai 14 PV e il cervello di un comodino.",
  13: "Numero fortunato. Ma non per te.",
  12: "In compenso, puzzi meno di prima.",
  11: "Il tuo corpo regge. La tua dignità molto meno.",
  10: "Sei a metà strada tra l’umiliazione e l’obitorio.",
  9: "Ogni movimento è un lamento. Ogni respiro un errore.",
  8: "Un tossico con l’asma fa più paura di te.",
  7: "Mezzo vivo, mezzo merda.",
  6: "Hai la vitalità di un Kallax in offerta.",
  5: "Hai 5 PV. E l’espressione di chi ha appena cagato sangue.",
  4: "A questo punto potresti esplodere se tossisci.",
  3: "Ti manca solo la bara e un parente ipocrita.",
  2: "Sei uno sputo dal baratro. Con il fiatone.",
  1: "Sei la sigaretta prima del plotone.",
  0: "SEI MORTO (COGLIONƏ)."
};

const CATEGORY_MAP: Record<string, Categoria> = {
  "Bilanciato": Categoria.Bilanciato,
  "Fruttato": Categoria.Fruttato,
  "Erbaceo": Categoria.Erbaceo,
  "Speziato": Categoria.Speziato,
};

const RAW_GINOCCHI_DETAILS_TEXT = `Numero del gindex	Nome	Tipologia	PV	Attacco 1	Potenza 1	EFFETTO 1	Attacco 2	Potenza 2	EFFETTO 2	Attacco 3	Potenza 3	EFFETTO 3	Attacco 4	Potenza 4	EFFETTO 4	Attacco 5	Potenza 5	EFFETTO 5	Attacco 6	Potenza 6	EFFETTO6	Descrizione
1	Punturirma	Bilanciato	19	Pera di gin	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si difende, chi attacca infligge danno +2.	Bocce stordenti	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Intubazione pandemica	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si difende, l’attaccante può bere un sorso e recuperare 2 PV.	Pasto ospedaliero	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Fascino della divisa	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Punturona penetrona	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Se questa maliarda procace, dalle forme sinuose e dagli occhi languidi, posa lo sguardo su di voi, sappiate che la vostra fine è imminente. Nata dalla perversione alchemica di un laboratorio segreto, cela dietro un sorriso mellifluo una inquietante propensione all'omicidio. Vi sussurra una puntura al giorno toglie il medico di torno con quel suo lessico aulico da Lucrezia Borgia, mentre impugna soluzioni iniettabili a base di gin tonic e veleno ofidico. Quante anime hanno già varcato la soglia dell'oblio, perse in un'euforia etilica fatale... Preparatevi a un'iniezione di paradiso, un attimo prima del vostro hard-reset.
2	Roboshop	Bilanciato	18	Roboprendo la vecchia	Danno: 2	Cura - Chi attacca recupera 2 PV.	Penetrazione robotica	Danno: 2	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Assistenza virtuanale	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Spesa a domicidio	Danno: 4	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Vibromassaggiatore assassino	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Drefammentami il disco e non fermarti mai	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Frutto di un'ingegneria domestica piegata da scopi più intimi, Roboshop si aggira tra le corsie di un supermarket. Osservandolo vi renderete conto della sua duplice natura. Questo gigante muscoloso, con gli occhi che brillano di seducente tecnologia, è stato programmato per essere il vostro sex toy definitivo, ma non senza difetti. La sua voce profonda vi farà cadere in trance mentre, a causa di un bug, potreste sentirlo bisbigliare: cazzo cibernetico rotante. Ogni giorno chiede qualche etto in più di mazzancolle al banco del pesce, mentre la signora in divisa lo osserva tra soggezione e un disturbante desiderio represso.
3	Robinario	Bilanciato	17	Doppio vomito	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si difende, chi attacca infligge danno +2.	Doppia scorreggia	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Autoerotismo poliamoroso	Danno: 3	Cura - Chi attacca recupera 2 PV.	Depressione collettiva	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Sbronza anaerobica	Danno: 3	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno. 	Gin al napalm	Danno: 4	Autolesionismo - Chi attacca subisce danno +2.	Quando vi imbatterete in Robinario, lui vi avvolgerà nel suo Abbraccio Delle Origini. Mormorando, sempre al plurale, che non sono un errore della natura, ma la prova vivente che la natura, a volte, si masturba di nascosto. Nato da un'orgia interrazziale talmente sbilanciata da far voltare lo sguardo anche agli dei, lui (loro), non conosce il sarcasmo, ma la violenza, oh, quella la comprende benissimo. Il serpente che porta addosso, sede del suo cervello, potrebbe stupirvi con un inquietante ...papà?, mentre le sue lacrime velenose concimano la foresta per renderla un inferno tossico. Il senso di disagio potrebbe durare per mesi.
4	Prepezio	Bilanciato	14	Entrata forzata	Danno: 2	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Scappellamento	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Bacioanale	Danno: 3	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Anfratto defraudato	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Cocknado	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Sodomia mineraria	Danno: 4	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Minchia, se Prepezio emerge dai deserti ferali del pianeta Anusia lo si sente pulsare sotto i piedi. È subito chiaro quale sia la sua missione: penetrare. Questo anellide supremo, una creatura glandoide lunga fino a tre chilometri, si insinua in ogni anfratto caldo e umido con strategie spietate. Può contorcersi, irrigidirsi, espandersi e scavare, lasciando dietro di sé un tracciato disgustosamente fertile che deforma l'ecosistema. Se proverete a ucciderlo lui si dividerà, e vi ritroverete circondati da frotte di striscianti falli senzienti. Ma non preoccupatevi: ha anche dei difetti.
5	Gorettore	Bilanciato	22	Rissa da Pub	Danno: 2	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Ubriachezza frustrata	Danno: 3	Autolesionismo - Chi attacca subisce danno +2.	Ansia da partita IVA	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Fatturazione elettronica	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	F24 a sorpresa	Danno: 2	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Danno all'erario	Danno: 2	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Ohé, se incrociate Gorettore, sappiate che siete al cospetto di un signor gorilla che, dopo aver aperto la partita IVA, ha perso fino all'ultimo briciolo di gioia. La sua vita è un'eterna lotta contro scadenze fiscali e clienti insolventi. Il suo povero cervello calcola l'IVA al 22% su ogni singola scelta del cazzo, anche al bancone del pub. Quel grosso gorilla verde, un tempo pieno di sogni e ambizioni, adesso ha solo l'espressione di chi ha appena ricevuto una cartella esattoriale... non gli resta che imprecare con un inconfondibile accento pugliese.
6	Guerraniglio	Bilanciato	19	Ti sparo	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Mi sparo su un piede	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Riproduzione come conigli	Danno: 2	Cura - Chi attacca recupera 2 PV.	Carota detonante	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si difende, chi attacca infligge danno +2.	Incursione lagomorfa	Danno: 3	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Esercitazione suicida	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Soldato, si prepari. Il Guerraniglio non è solo un fottuto coniglio, ma il risultato di troppo testosterone sintetico, una filosofia di vita basata su Clint Eastwood e un codice penale reinterpretato a cazzo di cane. Col piglio di un veterano di guerra, vi spiegherà che per lui la difesa personale non è solo legittima, ma inevitabile ed inequivocabile. Ogni parcheggio occupato o gin tonic annacquato si può trasformare in una scintilla bellica. Le sue braccia pelose vi faranno sognare e al contempo cacare addosso. Ma attenzione, la sua potenza sessuale è direttamente proporzionale al calibro delle sue munizioni. Nessuno è mai tornato vivo da una notte con lui.
7	Tossicozza	Bilanciato	18	Vulvochiusura bivalvica	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si difende, l’attaccante può bere un sorso e recuperare 2 PV.	Perla nucleare	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Orefizio imperscrutabile	Danno: 2	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Tossicazzo	Danno: 3	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Impepata di uranio	Danno: 3	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Marea nera endovenosa	Danno: 4	Cura - Chi attacca recupera 2 PV.	Sssshhh… splash… Tossicozza nasce dagli abissi più infetti del pianeta. Cresciuta tra scorie nucleari e rifiuti umani, la sua immagine è l'ultima che vedrete. Una conchiglia monumentale, un occhio verde gigantesco che pulsa di vita innaturale e una perla che vale più del PIL dell’eurozona. A meno di trenta metri da lei, inizierete a perdere i capelli, i vostri occhi sanguineranno prima di dissolvervi in particelle subatomiche. Le sue onde sonore subacquee recitano un chiaro fottiti e torna indietro. Il desiderio che nascerà in voi? Quello di non averla mai incontrata. Squish!
8	Scarabarman	Bilanciato	15	Cocktail ai metalli pesanti	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Bartending eccessivo	Danno: 4	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Alcolismo distruttivo	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Happy Hour tossico	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Vermouth radioattivo	Danno: 4	Cura - Chi attacca recupera 2 PV.	Shackeramento letale	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Hic! Burp! Nato da un amplesso profano tra un cervo gigante e un uomo di latta, Scarabarman è un barman irresistibile, ovvero la vostra condanna. Con le sue braccia meccaniche sa far volteggiare shakers incandescenti e il suo alito di gin arrugginito può sterminare una città. Siete liberi di scegliere come uscire dal suo bar: ubriachi fradici o morti stecchiti. È un alcolista incallito, e lo Sbronzo Di Ferro, un mix di assenzio, olio motore e disperazione, è il suo capolavoro. L’ultima persona che ha provato a rifiutarlo ha dichiarato di aver visto Dio. Hic!
9	Sborniadrago	Bilanciato	19	Respiro del drago ubriaco	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Pissing autoinflitto	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Bava alcolemica	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Etilofiamma ancestrale	Danno: 3	Cura - Chi attacca recupera 2 PV.	Volo barcollante	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Incendio digestivo	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Se incontrate lo Sborniadrago, fate attenzione ad offrirgli da bere. È un dannato snob che sbava mentre parla e dice cose a sproposito. La leggenda narra che la caduta dell’Impero Romano sia stata colpa sua, non dei barbari. Tutto per un bicchiere sbagliato. Non accetta drink senza guarnizione, e se gli date un gin tonic senza ghiaccio il vostro destino è segnato. Il suo fiato è un Negroni rovente a 120°C. Dopo il terzo gin tonic, la sua tolleranza alcolica si annulla, rendendolo ancora più pericoloso. Ah, preparatevi, insulterà vostra madre.
10	Tigrallo	Bilanciato	19	Ruggito neoborbonico	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Morso neomelodico	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Un euro a Piacer	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Fasti neobarocchi	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Digestione della bufala	Danno: 2	Cura - Chi attacca recupera 2 PV.	Chiagn e fott	Danno: 2	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Uè uè, se state pianificando una gita alla Reggia di Caserta, preparatevi a un'operazione di rimozione coatta di interiora. Il Tigrallo è un mostro dalla genetica assai intrigante (trattasi di un incrocio tra tigre e zebrallo) con una sofisticata passione per gli organi interni. Si aggira tra gli stucchi barocchi con un accento campano quasi insopportabile. Emana una sottile puzza di stalla, e fa strage di turisti colpevoli di aver confuso Caserta con Napoli. Non corre, trotta. Non azzanna, ma esegue accurate vivisezioni con tempistiche da chirurgo olimpionico. Gli zoccoli non sono un problema.
11	Roboraffa	Bilanciato	16	Ossiconi Assassini	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Allungamento	Danno: 4	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Morso erbivoro metallico	Danno: 3	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Coccolone letale	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Bioingegneria pansessuale	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Spada della fiamma giraffosa	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Davanti alla Roboraffa, inginocchiatevi o correte, figgiêu. Un esperimento di bioingegneria spinto troppo in là ci ha regalato questa giraffa fusa con una macchina da guerra. È una torre d’avorio con armi a impulsi integrate e pochissima resistenza emotiva. È molto potente, ma iper-sensibile: per una semplice osservazione sulla sua altezza potrebbe distruggere una città con una raffica di missili al napalm. La cosa più inquietante? Ha una dotazione biologica femminile completa e funzionante.
12	Florona	Erbaceo	16	Seduzione furry	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Bouquet di dildi	Danno: 4	Cura - Chi attacca recupera 2 PV.	Fiorellini birichini	Danno: 5	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Leccata di gatta	Danno: 4	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Coccolone peloso	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Dildo a sorpresa	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Il suo sguardo vi ipnotizza e la sua chioma ondeggia. La nostra Florona è una cazzo di entità sensuale fatta di polline e soffice pelo. Vi parlerà sempre con voce triste e pietosa. Era un’adorabile sexy gatta, sogno umido di ogni furry, ma ora, dopo l'incidente, spande intorno a sé agonia e sofferenza. Ogni primavera causa più vittime del tabacco, semplicemente stando lì, bellissima, elegante e piena di allergeni micidiali. Se provate a potare la sua maestà floreale, vi seppellirà in un tripudio di edera assassina e polline letale... Miao.
13	Ran-occhio	Erbaceo	15	Sputo del Gange	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Finocchiata	Danno: 4	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Spruzzo di girini	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Leccarospo sballotosto	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Finocchiona di anfibio	Danno: 4	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Aromaterapia estrema	Danno: 3	Cura - Chi attacca recupera 2 PV.	Se Ranocchio vi vede con un panino al prosciutto, siete già morti. Emerso dalle acque infette del Gange come incarnazione anfibia della vendetta vegetale, questo combattente del veganismo militante ha un accento marchigiano inconfondibile. È un coltivatore ossessivo di finocchi, e chiunque osi mettere in dubbio la qualità della sua merce viene sommerso da insulti, una sassaiola di verdure e un colpo secco di finocchio in piena faccia. L'unico modo per sopravvivere al suo sguardo di disprezzo? Gridare Lunga vita al tofu! e offrirgli un gin tonic con latte di avena.
14	Arundizilla	Erbaceo	20	Tosaerba erbaceo	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Conquista vegetale	Danno: 3	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Nuggets vegani	Danno: 3	Cura - Chi attacca recupera 2 PV.	Lancia di sedano	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Crociata crudista	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Zuppa di umani	Danno: 4	Cura - Chi attacca recupera 2 PV.	Burp! Quando vostra nonna vi diceva parla con le piante, che ti ascoltano, non parlava di Arundizilla. Lui è il risultato di un esperimento finito malissimo: un incrocio tra bambù geneticamente modificato, un giardiniere con un pollice troppo verde e il puro  terrore cosmico. Burp! Cresce incontrollato, divora tutto, e soprattutto non si può potare. Se lo mettete al sole, colonizzerà il pianeta in due ore. Burp! È un vegetariano carnivoro, ma solo per principio. Ogni tentativo di tagliarlo lo fa ricrescere più incazzato, costringendovi alla convivenza, come con un coinquilino tossico. Burp!
15	Gelsosauro	Erbaceo	17	Tirannomorso	Danno: 2	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Pissing dalla pelle	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Odio aromatico preistorico	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Urina corrosiva	Danno: 2	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Fioritura esplosiva	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Tirannocazzo	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Sticazzi! Il Gelsosauro è un Tyrannosaurus Rex mutato dai pollini e dall'invasività dei gelsomini, con un rutto di fiori marci che vi guasta l'anima. Figlio di uno scienziato pazzo che ha sottovalutato il rischio floreale, è diventato un casino di zanne e fiori. Non fatevi ingannare dalla sua fragranza delicata: espelle urina direttamente dai pistilli che ricoprono il suo corpo. Un getto caldo e corrosivo che vi lascerà campi e traumi permanenti. Consuma comunque venticinque chili di carne al giorno. Per il resto, caga normalmente.
16	Lavandasma	Erbaceo	17	Furto dell'anima	Danno: 3	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Incubo alla lavanda	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Bucato fantasmagorico	Danno: 2	Cura - Chi attacca recupera 2 PV.	Profumo letale	Danno: 2	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Essenza di morte	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Incubo profumato	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Parlando con Lavandasma, il suo tono depresso vi avvolgerà in un'aura di malinconia fatale. È lo spirito sconsolato di una giovane morta in un campo di lavanda, e la sua unica missione è succhiarvi l'anima. Parla così lentamente da far addormentare le sue vittime, per poi avvolgerle nei suoi fumi di morte. Consolatevi, perché lascerà un gradevole aroma nella vostra tomba. Non c'è possibilità di scappare, è solo il suo modo per farvi sentire un po' meglio, forse, nel vostro eterno riposo profumato.
17	Salviananda	Erbaceo	17	Colpo femminista	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Colpo ecologista	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Incatenata all'opera d'arte	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Eco-terrorismo letale	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Liana strangolatrice	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Ascia verde sangue	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Salviananda non è qui per le vostre petizioni cringe. Lei agisce, e col suo slang incomprensibile vi farà capire che il cambiamento climatico non si ferma con la raccolta differenziata, ma con una testa mozzata nel bidone dell’umido. Emissioni di CO₂? Diminuiranno rapidamente con qualche SUV in fiamme. Se avete mai detto sì, ma servono soluzioni realistiche e sostenibili, preparatevi a diventare concime per la sua nuova foresta. Produci più CO₂ di una seme di chia? Guardati le spalle.
18	Koajhonny	Erbaceo	21	Bicipite balsamico	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Caduta dall'albero	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Gola fresca e profonda	Danno: 2	Cura - Chi attacca recupera 2 PV.	Abbraccio asfissiante	Danno: 2	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Marsupio esplosivo	Danno: 2	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Fisting marsupiale	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	A primo acchito, Koajhonny vi sembrerà il sogno proibito di una casalinga annoiata: pettorali scolpiti, barba da taglialegna e uno sguardo che promette avventure. Ma non fatevi ingannare: sotto quella corazza da macho alpha, si nasconde un koala assassino con l’ormone in perenne ebollizione. Creato in laboratorio per infiltrarsi e sedurre gli umani fingendo di essere uno di loro, il suo appetito sessuale è pari a quello di un riccio nella stagione degli amori. Se non è impegnato a scalare alberi di eucalipto, lo troverete a letto con qualcuno che non avrà mai più una vita normale.
19	Rosiro	Erbaceo	18	Sguardo irresistibile	Danno: 3	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Petali di rosa	Danno: 2	Cura - Chi attacca recupera 2 PV.	Orgoglio Queer	Danno: 4	Cura - Chi attacca recupera 2 PV.	Parata orgiastica	Danno: 2	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Peli sudati e sudore peloso	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Fluido ipnotico	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Dolcezze, se Rosiro vi abbraccia, preparatevi a un'esperienza mistica che vi farà rivalutare ogni certezza, perché questo tapiro sinuoso dall'angosciante carica erotica vi parlerà come una sgualdrina disinibita. Le sue striature ipnotiche e i suoi occhi magnetici sono armi letali. Eterosessuali? Dopo una notte con Rosiro vi ritroverete con un Negroni in mano e un boa di piume al collo, senza il minimo dubbio su cosa sia successo. Non è solo un lussurioso. È un filosofo, un'icona vivente del desiderio senza etichette.
20	Rosella	Erbaceo	16	Shock pettoruto	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Rose transfemministe	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Penetrazione a sorpresa	Danno: 3	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Orgia infernale	Danno: 2	Cura - Chi attacca recupera 2 PV.	Stregoneria sodomita	Danno: 4	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Quartetto letale (seno e gonadi)	Danno: 2	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Se pensate di avvicinarvi a Rosella, sappiate che ha un pene. Il suo vocione da virgulto farà vibrare le vostre viscere, mentre i suoi occhi rossi vi fisseranno brillando di una malizia sboccata. È il frutto di un'antica, maledetta perversione che ha preso forma tra le luci di un luna park infernale. Questa creatura demoniaca con corna e ali vi avvolgerà in un'aura di peccato puro, con rose di carne che sbocciano sulla sua pelle straziata. È guidata da una lussuria contorta, capace di corrompere con una grazia che vi farà implorare di annegare nel vizio. Lasciatevi sedurre dal suo canto profondo e dal suo sguardo che promette abissi di piacere e perdizione.
21	Cybermint	Erbaceo	14	Sensualità cibernetica	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Vagina con firewall	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Cyberpeto mentolato	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Mojito lenitivo	Danno: 4	Cura - Chi attacca recupera 2 PV.	Esco le cyberminne	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Esco la cyberfregna	Danno: 4	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Se incontrate Cybermint, sappiate che si tratta dell'evoluzione tramite sviluppo AI di un robot aspirapolvere da serra intensiva. Lei vi parlerà come un'assistente virtuale anni 2000, e il suo corpo cibernetico, con ramificazioni elettroniche luminose, nasconde una peculiarità anatomica: una vagina piperita. Si è evoluta per ottimizzare la coltivazione della menta, e la sua interfaccia sensoriale è progettata per un'esperienza a dir poco rinfrescante. Preparatevi a un'interazione che vi farà rivalutare ogni concezione di piacere virtuale.
22	Rosmaruma	Erbaceo	17	Caccona aromatica	Danno: 2	Cura - Chi attacca recupera 2 PV.	Rosmarino invalicabile	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Rosmamore millenario	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Letame sepolcrale	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Defecazione distruttiva	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Pietrificato dal letame	Danno: 3	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Dormendo accanto a Rosmaruma, il suo pensiero si insinuerà nel vostro cervello: io sono la pace, l'immobilità, il profumo ultimo. Questo imponente mostro muschioso, con occhi blu cielo e corna di rosmarino, è la statua sacra dello zen, ma anche il motore di una digestione portentosa. Emette centoventi chili di letame al giorno, fertilizzando la terra con una potenza tale che la scienza ha smesso di interrogarsi su questo fenomeno. Voi sperimenterete i sogni più sereni, ma chi dorme troppo... si sveglierà nella merda.
23	Cetriolana ottava	Erbaceo	16	Regalità falliforme	Danno: 2	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Cetrioli birichini	Danno: 4	Cura - Chi attacca recupera 2 PV.	Sudditanza ortaggifera	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Incastro imperiale	Danno: 4	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Cetrioli a profusione	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Entra tutto signori	Danno: 4	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Seduta sul suo trono di ortaggi fallici, Cetriolana Ottava è la regina indiscussa del regno dei cetrioli. Il suo corpo è un mistero anatomico. Adornata di gioielli verde smeraldo, la sua carne è una cattedrale dell'accoglienza ortofrutticola, capace di ospitare fino a quindici cetrioli contemporaneamente. Corre voce che il suo harem vegetale non sia un vezzo, ma una fonte di energia mistica che le conferisce il dominio assoluto su chiunque incroci il suo sguardo aggressivo. Chiunque osi sfidarla verrà immediatamente trasformato in un umile cetriolino, destinato a unirsi alla sua sacra, umiliata collezione.
24	Rosmanguilla	Erbaceo	16	Pesce condito	Danno: 3	Cura - Chi attacca recupera 2 PV.	Amore interraziale	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Secrezioni anguillose sguillose	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Scivolata mortale	Danno: 2	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Scarica elettrica condita	Danno: 3	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Morso viscido ma saporito	Danno: 4	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Ssse il concetto di food porn avesse una forma biologica, sssarebbe Rosmanguilla, la vostra viscida gourmet che sssibila quando parla. Nata già aromatizzata con rosmarino e limone, e con una forma fallica imbarazzante, è convinta di essere una leggenda sssacra che protegge il mondo dalla banalità assoluta. Vedendo una padella, emette un sssibilo di disprezzo e vi lascia addosso un retrogusto di rimpianto. Non tenta di sssfuggire alla forchetta, aspetta sssolo di essere degnamente accompagnata da un buon vino.
25	Banona	Fruttato	17	Ti plano nel culo con una banana	Danno: 4	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Banana split	Danno: 4	Cura - Chi attacca recupera 2 PV.	Volo Chiquita	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Doppio selfie letale	Danno: 3	Cura - Chi attacca recupera 2 PV.	Bananus ti mangia	Danno: 1	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Ti blocco e ti segnalo	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Volete fare amicizia con Banona? Siete dei fottuti illusi. Lei non è mai stata amica di nessuno e non lo sarà mai, nemmeno a pagamento, con quella sua volgarità innata che vi prende a schiaffi. In sella al suo fido Bananus (una creatura a metà tra una banana marcia e l’incubo erotico di un fruttivendolo maledetto) si aggira nelle ombre del regno oscuro, spezzando sogni con un ghigno di pura indifferenza. Influencer di professione con più follower della famiglia reale, accetta donazioni ma solo a fondo perduto.
26	Tony Ephedrina	Fruttato	16	Amore per le droghe	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Trip sublinguale	Danno: 4	Cura - Chi attacca recupera 2 PV.	Cristalloni volanti	Danno: 5	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Euro messi male	Danno: 5	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Paranoie e tachicardia	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Morte da after	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	A cena o in bus, Tony Ephedrina con la voce di un bambino drogato vi sparerà addosso le sue teorie. Questo essere, che Madre Natura avrebbe creato sotto anfetamine per settantadue ore consecutive, è l'icona vivente della psiconautica urbana. Nelle sue vene scorrono linfa erbacea ed MDMA. I suoi capelli erbosi, a crescita rapidissima, assorbono qualsiasi sostanza chimica presente nell'aria. È convinto che il 5G stia leggendo i suoi pensieri e che ogni cartellone pubblicitario lo stia spiando. Il suo motto è they live, we sleep.
27	Cervarancio	Fruttato	17	Cazzo agrumato gargantuesco	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Buccia repellente	Danno: 4	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Cervopotenza ancestrale	Danno: 2	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Esplosione di polpa	Danno: 3	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Spremuta di muscoli	Danno: 3	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Corna cazzutissime del dio aranciato	Danno: 3	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Ecco il Cervarancio, l'abominio araldico nato dall'amore sacrilega tra un cervo e un'arancia sanguigna mutante, frutto a sua volta di esperimenti irresponsabili e di una spremuta infernale. Con i suoi occhi incandescenti scruta l’anima degli stolti che osano avvicinarsi, mentre le sue corna, cariche di agrumi esplosivi, vibrano di elettricità statica. Le sue zampe spezzano la terra rilasciando un'essenza agrumata inebriante ma tossica. Se osate assaporare uno dei suoi spicchi, la vostra lingua si dissolverà, ma i superstiti giurano sia talmente buono da volerlo rifare quanto prima.
28	Merlotta	Fruttato	14	Aratro voltaorecchio	Danno: 4	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Cultivar franche di piede	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Lieviti indigeni	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Fermentazione estrema	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Vinificazione crudele	Danno: 5	Cura - Chi attacca recupera 2 PV.	Tannino letale	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	De', la Merlotta è un monumento all'arte dell'autodistruzione enologica. Tra un sorso e l'altro, vi parlerà con accento toscano. La sua tenuta di quattrocento ettari è una dispensa di sbronze a ciclo continuo, ma esclusivamente per il suo personale consumo. Corre voce che butti giù la prima barrique prima dell'alba. Se le chiedete un bicchiere, vi allungherà il tubo dal suo tank da venti ettolitri, guardandovi con compassione per il vostro ridicolo tentativo di bere con moderazione. Senza un bicchiere in mano, tra i suoi filari, siete voi quelli fuori posto.
29	Corvananas	Fruttato	18	Seme profumato	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	619 senza l'one	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Wrestlermania 18	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Sottomissione fruttata	Danno: 4	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Becco afrodisiaco	Danno: 4	Cura - Chi attacca recupera 2 PV.	Pizza hawaii	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Madamin, il maestoso Corvananas saltafuori da un tragico esperimento culinario avvenuto in un bordello caraibico. Sorprendentemente, vi parlerà con quel suo accento piemontese, a suo modo seducente. Questa chimera muscolosa di piume nere e polpa gialla è pronta a farvi volare nel paradiso del piacere o dell’agonia. Il suo corpo, ricoperto da una ruvida corazza d'ananas, è perfetto per sessioni di massaggi esfolianti estremi. Talvolta lesivi. La sua presa aerea, il suo "Pineapple Express", vi ricopre di succo che ammorbidisce la carne e lascia un retrogusto tropicale, soprattutto nelle zone erogene. La dipendenza da queste sensazioni durerà almeno quarantotto ore.
30	Fiammaciofo	Fruttato	18	Incubo fiammeggiante	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Carciofo alla brace	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Multimasturbazione poli bukkakika	Danno: 2	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	La terra dei fuochi	Danno: 2	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Inquinamento carciofico	Danno: 2	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Carbonizzazione finale	Danno: 1	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Oh, Fiammaciofo è un semplice carciofo meridionale, ma ha acquisito caratteristiche che nessun vegetale dovrebbe mai avere: irradia calore, brilla al buio e toccandolo molto a lungo potreste sviluppare un terzo capezzolo. Con il suo accento molisano, vi dirà che non è ancora finito in un piatto stellato... per ora! Sta cercando di corrompere alcuni chef con sapori unici e un leggero retrogusto di roghi tossici. La sua carne è tenerissima, ma chi lo mangia riferisce sensazioni contrastanti tra l'estasi gastronomica e l'improvvisa voglia di fare una TAC.
31	Rosa cagnolina	Fruttato	15	Mammellone di rosa canina	Danno: 4	Cura - Chi attacca recupera 2 PV.	Gender gap vegetale	Danno: 2	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Spine dell'amore sopra ogni cosa	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Allattamento vegetale	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Morso proprio lì	Danno: 4	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Spezzacazzi	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Quando la natura si è rotta il cazzo della cementificazione, ha partorito Rosa Cagnolina, la materializzazione della sua ira botanica. Creata con pazienza millenaria, è un incrocio tra una driade incazzata e un cespuglio infestante, il suo sguardo brilla di rancore fotosintetico. Non si limita a far germogliare la vita: la usa per soffocarvi lentamente mentre enuncia nomi scientifici di piante velenose. I suoi seni, scandalosamente perfetti, producono bacche allucinogene che causano visioni di un mondo senza plastica. Se la incontrate, il suo strillo silenzioso vi porrà davanti a una scelta: diventare vegani, o diventare vegetali.
32	Pipimone	Fruttato	17	Aspra trascendenza	Danno: 2	Cura - Chi attacca recupera 2 PV.	Diaconato agrumato	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Ultrasuoni sacri	Danno: 4	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Minzione divina	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Getto purificatore	Danno: 2	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Ostia al limone	Danno: 3	Cura - Chi attacca recupera 2 PV.	Ajò, il Pipimone è maestoso, divino, ma palesemente sbagliato. Questo ibrido nato dal matrimonio nefasto tra l’eleganza di un pipistrello sacro e la sfiga genetica di avere un limone al posto dello scroto, spruzza succo citrico in aria ogni volta che sbatte le ali. Durante la stagione degli amori, l'aria si riempie di un aroma acidulo che fa correre ai ripari ogni umano sulla faccia delle terra. Berreste davvero una limonata, sapendo che potrebbe contenere l'essenza delle sue gonadi divine?
33	Eremillo	Fruttato	19	Saggezza antica e un pò sopravvalutata	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Mirtillata malata	Danno: 3	Cura - Chi attacca recupera 2 PV.	GDILF	Danno: 2	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Vita senza defecazione	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Antiossidante pazzesco	Danno: 2	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Respiro ai mirtilli	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	L'Eremillo vaga tra le montagne più alte del mondo da oltre due secoli, nutrendosi solo di mirtilli e ignorando completamente la civiltà umana. Il suo corpo, tempio di purezza e saggezza, è forgiato dal gelo e da un’alimentazione così ricca di antiossidanti che il tempo stesso si è arreso contro di lui. Non invecchia, non si ammala, non si sporca. Non fa nemmeno i suoi bisogni. Il suo profumo naturale di mirtilli vi avvolgerà, ma attenzione: non ha mai visto una donna in vita sua, e il primo che prova a spiegargli cosa sia il sesso rischia di essere disintegrato con una sola e devastante occhiata confusa.
34	Mangodillo	Fruttato	19	Jackpot del cingolato	Danno: 3	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Una rondine andata via	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Ludopatia tropicale	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Mangodillo vende un rene	Danno: 3	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Mangodillo compra un rene	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Slot machine vertebrale	Danno: 2	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Ovunque lo incontriate, il Mangodillo, vi canterà la sua triste storia di star cadura in rovina: Ooooh, io ero la suuuuperstar, la voce più seducente e tropicale che il mondo animale avesse mai conosciuto, oh... Poi però sono arrivati i casinò. Le luci delle slot machine lo hanno accecato e fatto sprofondare nel tunnel della ludopatia. L’unico frutto che lo attrae non è più il mango, ma quello maledetto dell’azzardo. Non canta più, ma gioca senza sosta, sperando che la prossima giocata gli restituisca tutto quello che ha perso.
35	Lampolpo	Fruttato	18	Amore tentacolare	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Ventose succhiatrici	Danno: 3	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	o' Purp 'mbuttunat	Danno: 3	Cura - Chi attacca recupera 2 PV.	Tentacolo orefiziale	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Lamponi nel culo	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Stritolapalle ai frutti di bosco	Danno: 2	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Diciamocelo chiaramente: il Lampolpo è il risultato del delirio di uno chef troppo ambizioso e di un regista giapponese con gusti un po' strani. Non stupitevi se vi parlerà con l'accento abruzzese di una zia incazzata. A metà tra un polpo da carpaccio e una macedonia maledetta, questa creatura non sa se vuole essere mangiata o solo guardata con sgomento. La sua acidità di frutti rossi gli ha conferito un’espressione perennemente incazzata. Il suo curriculum nel cinema giapponese è lungo quanto un suo tentacolo, con apparizioni in film vietati ai minori e nei peggiori hentai di nicchia. Il suo inchiostro è afrodisiaco, e chi lo inghiotte prova una strana combinazione di estasi e pentimento cosmico.
36	Delfimaru	Fruttato	17	Shuriken delfinici	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Sfintere ninja	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Perversione delfinica	Danno: 2	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Tecnica ninja del delfino curioso	Danno: 4	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Kunai di arancia e sangue	Danno: 4	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Nuotata kamikaze	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Nel caso te lo stessi chiedendo, Delfimaru non è un cazzo di delfino. È un incubo ninja addestrato severamente nelle arti del ninjutsu. Attacca con pura, fredda brutalità, e i suoi colpi sono letali. Nato nel cuore del Villaggio Delle Arance, si muove tra le onde senza fare rumore, colpendo prima che la vittima possa capire cosa stia succedendo. Le sue pinne sono lame affilate, i suoi occhi due fottuti rubini assetati di sangue. La sua gente lo ha cresciuto nel culto dell’arancia, sacra fonte di vitamina C. Una fetta d'arancia è probabilmente l’ultima cosa che vedrete nella vostra vita.
37	Pignacano	Fruttato	18	Pinoli penetranti	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Piume ignifughe ma brutte	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Beccata di tristezza	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Seme rancoroso	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Depressione tucanica	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Partenogenesi letale	Danno: 4	Cura - Chi attacca recupera 2 PV.	Se fissate con coraggio il Pignacano, lui vi guarderà con i suoi occhi tristi e vi sputerà un pinolo in faccia, imprecando con le sue parolacce preferite. Questo tragico volatile, metà tucano indemoniato e metà scultura di corteccia, non ha organi sessuali e non conosce il piacere fisico. Per riprodursi, deve ingoiare rapidamente dieci pigne e poi sputare pinoli con una precisione da cecchino. Le sue piume sono fatte di squame di legno e dal suo becco sgorga miele ma lui non lo sa, questo solo perché l’universo ha deciso di renderlo ancora più disturbante.
38	Pompecora	Fruttato	19	Aspra lana	Danno: 2	Cura - Chi attacca recupera 2 PV.	Sbucciare un esperidio	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Pom-pecorina	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Tosatura selvaggia	Danno: 2	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Rutto alcolico	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Zoccolo frantumacazzi	Danno: 3	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Lo sguardo di Pompecora brucia come la vostra esofagite dopo un succo d'arancia a stomaco vuoto. È palesemente ubriaca. Lei è la prova vivente che il consumo eccessivo di pompelmo porta alla follia mistica. Le sue giornate passano tra spremiture compulsive, rituali alcolici e occasionali sacrifici agli dèi del fermentato artigianale. Il suo vero vino di pompelmo va affinato con ossa umane, lacrime di astemi e una bestemmia detta sottovoce. Con la sua Spremitura Eruttiva, vi sputerà in faccia un getto di succo acido, infliggendovi nausea permanente e crollo della vostra dignità.
39	Winenot?	Fruttato	16	Sensualità furry	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Molti bicchieri di vino	Danno: 4	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Potenza radical chic	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Bevuta ammosciante	Danno: 3	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Sciabolata da gigolò	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Sbronza mattutina	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Winenot proverà a sedurvi con il suo lessico forbito, ma sappiate che è un gigolò trasformato in un pedante connoisseur di vini naturali con una fortissima R moscia. Un tempo banale sciupafemmine da salotto, ha scoperto i vini naturali e da allora non parla d'altro. Ogni conversazione si trasforma in un monologo sull'importanza della fermentazione spontanea e sulla superiorità morale del biodinamico. Vi bombarderà con nomi di viticoltori sloveni mai sentiti. Il suo fascino è inspiegabile, un mix letale tra pelo folto e cultura. Il suo sguardo dice: sono meglio io, irresistibile per chiunque abbia un minimo di autostima da mettere in discussione.
40	Callista	Speziato	17	Necrofilia indotta	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Resurrezione per futili motivi	Danno: 2	Cura - Chi attacca recupera 2 PV.	Putrefazione avanzata	Danno: 4	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Cripto-overdose	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Bitcoin cimiteriali	Danno: 4	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Lapide per phishing	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Callista un tempo era un'anima pura e solare, raggiante di speranza e positività. Amava i tramonti, le tisane e credeva nell’umanità. Poi ha scoperto le criptovalute. Ora la sua anima è corrotta oltre ogni possibilità di redenzione e la sua allegria è maniacale. Non parla d'altro che di NFT, token e rendite passive, e chiunque osi guardarla negli occhi viene ipnotizzato in un vortice di investimenti che non porteranno mai a nulla. La sua voce è un sussurro malevolo che riecheggia nella notte: "Ehi fratello, vuoi guadagnare senza fare un cazzo?", e se rispondete sì, siete fottuti.
41	Cannellorca	Speziato	20	Affondanavi speziato	Danno: 4	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Colpo idrofobo	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Grasso che cola	Danno: 2	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Tsunami alla cannella	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Ondata Macellatrice	Danno: 2	Spinta - Chi attacca spinge l’avversario di 2 caselle nella direzione dell'attacco. Se l’avversario sbatte contro una parete del campo da gioco, perde 1 PV. Se l’avversario sbatte contro un altro personaggio in gioco, entrambi perdono 1 PV.	Fauci del giovedì	Danno: 1	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Se sentite il rombo di Cannellorca, preparatevi, perché è un leviatano speziato, flagello dei mari, e la sua minaccia è chiara: il mare è mio, e anche tu. Non è il cazzo di Willy che salta gli scogli, ma un demone delle profondità, aggressivo e minaccioso. Ovunque passi, l’oceano si macchia di una scia mortifera, tutta sangue e cannella. Le sue fauci grondanti non si chiudono senza strappare carne, tingendo le onde di un rosso speziato. La sua unica debolezza è la cioccolata: un profumo di fondente può placarlo per un attimo, prima di tornare all'attacco. Odia il giovedì.
42	Anicinzia	Speziato	18	Magia del Rasentin	Danno: 2	Cura - Chi attacca recupera 2 PV.	Stregoneria veneta	Danno: 4	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Arcanomanzia balsamica	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Ghiacciolo anosospinto	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Sambuca stordente	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Sbornia dolce	Danno: 2	Cura - Chi attacca recupera 2 PV.	Anicinzia, la maga veneta e ubriaca, vi fissa con un sorriso inquietante e il bastone d'anice in pugno. È una dannata leggenda che ha scoperto il vero potere nell’anice, ingurgitando così tante bottiglie di pastis e sambuca che il suo corpo è ormai una distilleria ambulante. Il suo sangue è una soluzione alcolica al settanta percento, e il suo respiro potrebbe infiammare un caminetto spento. Se provate a offrirle un drink che non sappia di anisetta e morte, vi guarderà con disprezzo e, senza dire una parola, trasformerà il vostro cocktail in un intruglio a base di anice. I villaggi devastati dopo il suo passaggio sono la prova che Anicinzia non beve mai da sola.
43	Fumello	Speziato	17	Ganja power	Danno: 2	Cura - Chi attacca recupera 2 PV.	Cartina aromatica	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Stonamento	Danno: 3	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Bomba spliff	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Paranoie da sballato	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Lasciami due tiri MAN	Danno: 3	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Hey mans, se beccate Fumello fateci caso, lui è l'incarnazione vivente dello stay irie, e vi parlerà come un rastafariano. Un'anima che vibra con le onde della natura, un mistico del verde che ha elevato il concetto di one love a un livello ultraterreno. Il tempo per lui è un'illuSione imposta da Babylon, e il mondo si divide tra chi sa rollare bene e chi deve ancora svegliarsi. Chi porta vibrazioni negative nella sua giungla rischia di finire avvolto in una nuvola da cui non si sveglia più.
44	Peperonbro	Speziato	18	Malavita piccante	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Non fottere con me	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	La vida loca è malata	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Per i fratelli ingiustamente carcerati	Danno: 4	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Jalapeño in pegno	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Capo gang aromatica	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Oh bro, senti come picca! vi dirà Peperonbro, il boss della Scoville, abbassando il finestrino della sua macchina pimpata. Non è un cazzo di peperoncino qualunque, ma il terrore che fa sudare anche i più duri. Leccare una delle sue dita equivale a un viaggio mistico in terapia intensiva, perché lui fuma sigarette arrotolate con le lacrime di quelli che hanno provato a mangiarlo. Se vi tocca, il vostro stomaco entra direttamente nel Programma Protezione Testimoni. Nessuno sopravvive per raccontarlo senza perdere almeno due organi.
45	Blobaffè	Speziato	19	Caffè sospeso	Danno: 3	Cura - Chi attacca recupera 2 PV.	Scordammc' o passat	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Tazzulella	Danno: 3	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Espresso bollente	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Caffè vista Vesuvio	Danno: 2	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Mostruosità partenopea	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Ué, se Blobaffè vi si para davanti sono cazzi. Il demone liquido che infesta il Golfo di Napoli, nato dall’eccesso di generosità partenopea e da una serie infinita di caffè sospesi mai riscossi. Questa bestia torbida sprigiona vapori soffocanti di tostatura e condanna i miseri a un’agonia di veglia perpetua. Non vi uccide col ferro né col fuoco: vi desta, vi scuote, vi rende vigili oltre il limite della sopportazione, finché il cuore non cede e le vene si fanno dure come una tazzina. Nelle notti di scirocco sentirete un fischio risalire dal golfo: o'vuò nu cafè? bisbiglia, con voce soave e letale.
46	Speziatopo	Speziato	19	Spaccio di pepi	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	La rogna	Danno: 2	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Orecchie da mercante	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Dose letale	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Formaggio drogato	Danno: 3	Cura - Chi attacca recupera 2 PV.	Topo kamikaze	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Priviet! Il piccolo Speziatopo, re della polvere fine e alchimista di quartiere, con suo russo impeccabile vi proporrà un pizzico di pepe di Sichuan che come minimo vi paralizzerà la lingua. Le sue operazioni sono furtive e precise, si muove tra i banchi del mercato con la rapidità di una saetta. Non vende solo spezie, vende esperienze: roba che quando la mettete sulla lingua vi fa vedere la Madonna in trip di paprika. Se le cose si mettono male, puff! Scompare in una nube di polvere di cumino e riappare un po' più in là, pronto a servire il prossimo cliente con un sorriso da roditore e una bustina di pepe lungo che vi farà sbirciarel’aldilà.
47	Borghesiglio	Speziato	18	Opulenza polentona	Danno: 3	Cura - Chi attacca recupera 2 PV.	Fascino di chi c'ha i soldi	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Riproduzione come conigli	Danno: 4	Cura - Chi attacca recupera 2 PV.	Scacco matto massonico	Danno: 4	Sorso salvifico - Se il bicchiere di chi attacca contiene più gin tonic di quello di chi si defende, l’attaccante può bere un sorso e recuperare 2 PV.	Bonifico istantaneo	Danno: 3	Succhiaggio PV - Chi attacca recupera PV pari al danno che infligge.	Martiny dry a  25€	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Oh figa, il Borghesiglio è il re indiscusso della sboronata pettinata. Nato e cresciuto ad Arcore, si rivolgerà a voi in un milanese da manuale. Con la sua giacchetta sartoriale e il monocolo d’oro, vi squadrerà con quell'aria da sciuro che vi fa sentire un povero tapino. Cena all-you-can-eat? Vi riderà in faccia, tra un sorso di gin premiume un affare con qualche industriale lombardo. Si orega di prendere appuntamento.
48	Teabear	Speziato	18	Zanna della teina dopante	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Tazza di the sanguinoso	Danno: 4	Cura - Chi attacca recupera 2 PV.	Ruggito dell'orso mangiabambini	Danno: 2	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Infuso di the e cadaveri	Danno: 2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Bollitore ursinico diabolico	Danno: 2	Blocca attacco - Chi si difende non potrà attaccare al prossimo turno.	Orsoteina letargica	Danno:2	Ammosciamento - Chi si difende infliggerà danno massimo 1 al prossimo attacco.	Se vi avventurate in Siberia, il pericolo più grande non è il gelo, ma Teabear, un orso spietato che si crede un intellettuale. Con la sua parlata balcanica, vi spiegherà che, dopo aver imparato il galateo britannico squartando un campeggiatore, non uccide senza prima aver sorseggiato una tazza di Earl Grey. Le sue regole sono ferree: mai saltare l’infuso delle cinque, mai mettere lo zucchero nel tè (perché lo zucchero è volgare, meglio del sangue fresco) e mai farlo incazzare. L’ultima persona che ci ha provato adesso è un thé verde.
49	Tzatzikeye	Speziato	20	Antipasto assassino	Danno: 4	Cura - Chi attacca recupera 2 PV.	Muffa cetriolifera	Danno: 4	Alcolismo competitivo - Se il bicchiere di chi attacca contiene meno gin tonic di quello di chi si defende, chi attacca infligge danno +2.	Insalata greca	Danno: 2	Cura - Chi attacca recupera 2 PV.	Diarrea esplosiva	Danno: 3	Inverti casella - Per chi si difende, il bonus “gioco in casa” (se applicabile) diventa un malus di pari valore.	Emorroidi galattiche	Danno: 2	Paralisi totale - Chi si difende non puoi muoversi né attaccare al prossimo turno.	Cetriolo rettale rettificato	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	TzatzikEye è una povera salsa dimenticata nel frigo del vostro peggior incubo, e ora è qui per vendicarsi in modo molto volgare. Evoluta in una divinità di disgusto e punizione che gli antichi avrebbero temuto e venerato, questa creatura con l'occhio fermentato vi guarda dentro e giudica ogni vostra scelta alimentare, specialmente se avete mai osato ordinare una pizza all'ananas, stronzi. Le sue muffe senzienti producono un siero maledetto. Una sola goccia può rovinare la vostra insalata, scatenando diarrea fulminante e crampi esistenziali. Il suo reflusso olimpico vi ricoprirà con una massa yogurt rancido. Impossibile uscirne.
50	Fuega	Speziato	18	Piccantezza in straming	Danno: 4	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Plug di cajenna	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Un miliardo di Punti scoville	Danno: 3	Paura - Chi si difende, nel prossimo turno non potrà avvicinarsi a chi ha attaccato, dovrà rimanere ad almeno una casella di distanza.	Dildo di fuoco	Danno: 3	Spogliato - Chi si difende non potrà difendersi al prossimo attacco.	Tortura piccante	Danno: 5	Autolesionismo - Chi attacca subisce danno +2.	Onlyfans letale	Danno: 3	Vilipendio - Chi si difende, se di sesso diverso da chi attacca, subisce danno doppio.	Se i vostri occhi si posano su Fuega, sappiate che state guardando la divinità infuocata del capsicum. Nata nell'umile orto di famiglia, cerca rivalsa con il suo progetto imprenditoriale: porno piccanti, letteralmente. Quanti modi ci sono per usate un peperoncino? Lei, con la sua chioma ardente e gli occhi che bruciano di una malizia antica, è la prova che il piccante è alle porte della perdizione. Ogni peperoncino che brandisce è una promessa di dolore sublime, un'estasi di sudore e bruciore che vi farà implorare pietà. Accetta solo bonifici istantanei.
`;

const parseDamageString = (damageStr: string): string => {
  // Normalize "Danno: Danno: X" to "Danno: X"
  const doubleDamageRegex = /Danno: (Danno: \d+)/i;
  const match = doubleDamageRegex.exec(damageStr);
  if (match && match[1]) {
    return match[1];
  }
  // Ensure "Danno:X" becomes "Danno: X"
  // Also handles cases like "Danno:3" or "Danno: 3" to ensure it's "Danno: 3"
  // And ensures "Danno:Danno: X" from bad copy-paste is still handled if the first regex doesn't catch it due to casing or slight variations.
  let normalized = damageStr.replace(/Danno:Danno:/gi, 'Danno:'); // Catch "Danno:Danno:" regardless of case
  normalized = normalized.replace(/Danno:(\d+)/gi, 'Danno: $1'); // Ensure space after colon
  return normalized.trim();
};

const parseAllGinocchiData = (): { ginocchi: Ginocchio[], descriptions: Record<number, string> } => {
  const lines = RAW_GINOCCHI_DETAILS_TEXT.trim().split('\n');
  const headerLine = lines[0].split('\t').map(h => h.trim());
  const ginocchiArray: Ginocchio[] = [];
  const descriptionsMap: Record<number, string> = {};

  const colIndices = {
    id: headerLine.indexOf('Numero del gindex'),
    nome: headerLine.indexOf('Nome'),
    tipologia: headerLine.indexOf('Tipologia'),
    pv: headerLine.indexOf('PV'),
    descrizione: headerLine.indexOf('Descrizione'),
    attacchi: [] as { nome: number, potenza: number, effetto: number }[]
  };

  for (let i = 1; i <= 6; i++) {
    colIndices.attacchi.push({
      nome: headerLine.indexOf(`Attacco ${i}`),
      potenza: headerLine.indexOf(`Potenza ${i}`),
      // Correctly find "EFFETTO6" for the 6th attack, and "EFFETTO X" for others
      effetto: headerLine.indexOf(i === 6 ? `EFFETTO6` : `EFFETTO ${i}`)
    });
  }
   // Verify indices (for debugging, can be removed later)
  // console.log("Column Indices:", JSON.stringify(colIndices, null, 2));


  for (let i = 1; i < lines.length; i++) {
    const cells = lines[i].split('\t').map(c => c.trim());
    if (cells.length < headerLine.length) {
        // console.warn(`Skipping line ${i+1} due to insufficient cells: ${cells.length} vs ${headerLine.length}`);
        continue;
    }


    const id = parseInt(cells[colIndices.id], 10);
    const nome = cells[colIndices.nome];
    const tipologiaStr = cells[colIndices.tipologia];
    const pvIniziali = parseInt(cells[colIndices.pv], 10);
    const descrizione = cells[colIndices.descrizione];

    if (isNaN(id) || !nome || !tipologiaStr || isNaN(pvIniziali) || !descrizione) {
    //   console.warn(`Skipping line ${i+1} due to invalid basic data: ID=${id}, Nome=${nome}, Tipologia=${tipologiaStr}, PV=${pvIniziali}`);
      continue;
    }

    const categoriaEnum = CATEGORY_MAP[tipologiaStr] || Categoria.Bilanciato; 
    const immagine = `/images/ginocchi/${id}.png`;

    const attacchi: Attacco[] = [];
    colIndices.attacchi.forEach((attaccoIndices, index) => {
      // Ensure indices are valid before accessing cells
      if (attaccoIndices.nome === -1 || attaccoIndices.potenza === -1 || attaccoIndices.effetto === -1) {
        // console.warn(`Missing attack column indices for Ginocchio ID ${id}, Attack ${index + 1}. NomeIdx: ${attaccoIndices.nome}, PotIdx: ${attaccoIndices.potenza}, EffIdx: ${attaccoIndices.effetto}`);
        return; // Skip this attack if column indices are not found
      }

      const nomeAttacco = cells[attaccoIndices.nome];
      const potenzaAttacco = cells[attaccoIndices.potenza];
      const effettoAttacco = cells[attaccoIndices.effetto];
      
      if (nomeAttacco && potenzaAttacco && effettoAttacco) {
        attacchi.push({
          dado: index + 1,
          nome: nomeAttacco,
          danno: parseDamageString(potenzaAttacco),
          effetto: effettoAttacco
        });
      } else {
        // console.warn(`Missing data for Ginocchio ID ${id}, Attack ${index + 1}: Nome='${nomeAttacco}', Potenza='${potenzaAttacco}', Effetto='${effettoAttacco}'`);
      }
    });
    
    if (attacchi.length < 6) {
        // console.warn(`Ginocchio ID ${id} (${nome}) only has ${attacchi.length} attacks parsed. Expected 6.`);
    }


    ginocchiArray.push({
      id,
      nome,
      categoria: categoriaEnum,
      colore: CATEGORY_COLORS[categoriaEnum],
      immagine,
      attacchi,
      pvIniziali
    });
    descriptionsMap[id] = descrizione;
  }
  return { ginocchi: ginocchiArray, descriptions: descriptionsMap };
};

const parsedData = parseAllGinocchiData();
export const ALL_GINOCCHI: Ginocchio[] = parsedData.ginocchi;
export const GINOCCHIO_DESCRIPTIONS: Record<number, string> = parsedData.descriptions;