
import { Categoria, Ginocchio, Attacco } from './types';

export const CATEGORY_COLORS: Record<Categoria, string> = {
  [Categoria.Bilanciato]: '#CDBB00',
  [Categoria.Fruttato]: '#ca1828',
  [Categoria.Erbaceo]: '#45AD63',
  [Categoria.Speziato]: '#0072BB',
};

export const CATEGORIES_ORDER: Categoria[] = [
  Categoria.Bilanciato,
  Categoria.Erbaceo,
  Categoria.Fruttato,
  Categoria.Speziato,
];

export const APP_TITLE = "GINDEX";

export const PV_QUOTES: Record<number, string> = {
  22: "Nessuno ti ha ancora picchiato. È solo questione di tempo.", // Added for Gorettore
  21: "Nessuno ti ha ancora picchiato. È solo questione di tempo.",
  20: "Troppa energia. Sei già insopportabile.",
  19: "Troppo sano per essere simpatico.",
  18: "Sei come le emorroidi: difficile da eliminare.",
  17: "Sei ancora in piedi. Come un coglione.",
  16: "Sei lucido. Ed è un problema.",
  15: "Ti senti invincibile ma sei solo patetico.",
  14: "Hai 14 PV e il cervello di un comodino.",
  13: "Numero fortunato. Ma non per te.",
  12: "In compenso, puzzi meno di prima.",
  11: "Il tuo corpo regge. La tua dignità molto meno.",
  10: "Sei a metà strada tra l’umiliazione e l’obitorio.",
  9: "Ogni movimento è un lamento. Ogni respiro un errore.",
  8: "Un tossico con l’asma fa più paura di te.",
  7: "Mezzo vivo, mezzo merda.",
  6: "Hai la vitalità di un Kallax in offerta.",
  5: "Hai 5 PV. E l’espressione di chi ha appena cagato sangue.",
  4: "A questo punto potresti esplodere se tossisci.",
  3: "Ti manca solo la bara e un parente ipocrita.",
  2: "Sei uno sputo dal baratro. Con il fiatone.",
  1: "Sei la sigaretta prima del plotone.",
  0: "Sei morto (coglionə)."
};

const CATEGORY_MAP: Record<string, Categoria> = {
  "Bilanciato": Categoria.Bilanciato,
  "Fruttato": Categoria.Fruttato,
  "Erbaceo": Categoria.Erbaceo,
  "Speziato": Categoria.Speziato,
};

const CATEGORY_TO_FOLDER_NAME: Record<Categoria, string> = {
  [Categoria.Bilanciato]: "Bilanciati",
  [Categoria.Fruttato]: "Fruttati",
  [Categoria.Erbaceo]: "Erbacei",
  [Categoria.Speziato]: "Speziati",
};


const RAW_GINOCCHI_DETAILS_TEXT = `Numero del gindex	Nome	Tipologia	PV	Attacco 1	Potenza 1	EFFETTO 1	Attacco 2	Potenza 2	EFFETTO 2	Attacco 3	Potenza 3	EFFETTO 3	Attacco 4	Potenza 4	EFFETTO 4	Attacco 5	Potenza 5	EFFETTO 5	Attacco 6	Potenza 6	EFFETTO6	Descrizione
1	Punturirma	Bilanciato	19	Pera di gin	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Bocce stordenti	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Intubazione pandemica	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Pasto ospedaliero	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Fascino della divisa	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ago nel midollo	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Quando questa maliarda procace, dalle forme sinuose e dagli occhi languidi, posa lo sguardo su di voi, sappiate che la vostra fine sarà inebriante. Nata dalla perversione alchemica di un laboratorio segreto, ella cela dietro un sorriso mellifluo una propensione all'omicidio tramite soluzioni iniettabili a base di gin tonic e veleno ofidico. Vi sussurra con quel suo lessico aulico da Lucrezia Borgia: "Una puntura al giorno toglie il medico di torno", e novecentonovantanove anime hanno già varcato la soglia dell'oblio, inebriate da un'euforia etilica fatale. Preparatevi a un'iniezione di paradiso, prima del vostro hard-reset gastrico.
2	Roboshop	Bilanciato	18	Carrello di agrumi	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Penetrazione robotica	Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Assistenza virtuale	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Spesa a domicilio	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Vibromassaggiatore assassino	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Upgrade terminale	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Quando Roboshop, frutto di un'ingegneria domestica deviata verso scopi più… intimi, avanza nel supermercato, vi renderete conto della sua duplice natura. Questo gigante muscoloso, con quegli occhi che brillano di una tecnologia seducente, è stato riprogrammato per essere il vostro sex toy definitivo, ma non ha perso il suo tocco commerciale. La sua voce baritonale vi farà cadere in trance mentre, a causa di un bug, vi sentirete bisbigliare: cazzo cibernetico rotante. Ogni volta si fa aggiungere qualche etto in più di mazzancolle dalla signora della pescheria, che lo osserva tra soggezione e desiderio represso.
3	Robinario	Bilanciato	17	Doppio vomito	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Doppia scorreggia	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Autoerotismo poliamoroso	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Depressione collettiva	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Sbronza anaerobica	Danno: 3	Paralisi totale -Il Ginocchio attaccato non può muoversi né attaccare al prossimo turno (non cumulabile) 	Gin al napalm	Danno: 4	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Se vi imbatterete in Robinario, lui vi avvolgerà nel suo "Abbraccio delle Origini", sussurrandovi, sempre al plurale, che non sono un errore della natura, ma "la prova vivente che la natura, a volte, si fa delle gran canne". Nato da un'orgia interraziale così sbilanciata che gli dei stessi hanno girato lo sguardo, lui, cresciuto tra muschio e fango, non conosce il sarcasmo, ma la violenza, oh, quella la comprendiamo benissimo. Il serpente sulla sua spalla, che è il suo vero cervello, vi sussurrerà cose inquietanti tipo "Papà?", mentre le sue lacrime velenose continuano a trasformare la foresta in un inferno tossico, lasciandovi un senso di disagio che durerà mesi.
4	Prepezio	Bilanciato	14	Entrata forzata	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Scappellamento	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Bacioanale	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Tunneling sgradevole	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Cocknado	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Sodomia mineraria	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Signuri, quando PrepEzio emerge dai deserti mortali del pianeta Anusia, lo sentite pulsare sotto i piedi, e capite che la sua unica missione è penetrare. Questo anellide supremo, una creatura glandoide lunga fino a tre chilometri, si insinua in ogni anfratto caldo e umido con un’abilità inumana. Può contorcersi, irrigidirsi, espandersi e scavare, lasciando dietro di sé un tracciato disgustosamente fertile che stravolge l'ecosistema. Se provate a ucciderlo, si divide, e vi ritrovate circondati da un'orda di striscianti falli senzienti. Ma non preoccupatevi: caga normalmente.
5	Gorettore	Bilanciato	22	Rissa da Pub	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Ubriachezza frustrata	Danno: 3	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Ansia da partita IVA	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Fatturazione elettronica	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Resa dei conti	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Contusione letale	Danno: Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Aoh, se incrociate Gorettore, sappiate che state guardando un gorilla che, dopo aver aperto la partita IVA, ha perso ogni barlume di gioia. La sua vita è un'eterna lotta contro scadenze fiscali e clienti che non pagano, e il suo cervello calcola l'IVA al 22% su ogni singola, fottuta scelta, pure al bancone del pub. Quel Gorilla verde, un tempo pieno di sogni e ambizioni, adesso ha solo l'espressione di chi ha appena ricevuto una cartella esattoriale con un accento pugliese inconfondibile. E per voi, non ci sono ferie.
6	Guerraniglio	Bilanciato	19	Ti sparo	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Mi sparo su un piede	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Riproduzione come conigli	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Carota detonante	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Incursione lagomorfa	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Esercitazione suicida	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Soldato, preparatevi. Guerraniglio non è un cazzo di coniglio, ma il risultato di troppa testosterone sintetica e una filosofia di vita basata su Clint Eastwood e un codice penale reinterpretato a cazzo di cane. Vi parlerà con la voce di un veterano di guerra, spiegandovi che per lui, la difesa non è solo legittima, ma inevitabile ed esplosiva. Ogni parcheggio occupato o gin tonic annacquato si trasforma in una zona di guerra. Le sue braccia pelose vi faranno sognare e al tempo stesso vi metteranno a disagio, ma la sua potenza sessuale è direttamente proporzionale al calibro delle sue munizioni. Nessuno è mai tornato vivo da una notte con lui.
7	Tossicozza	Bilanciato	18	Vulvochiusura bivalvica	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Perla nucleare	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Orefizio imperscrutabile	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Scorza tossica	Danno: 3	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Bivalve tossicodipendente	Danno: 3	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Marea nera endovenosa	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Sssshhh… splash… gurgle… Tossicozza è nata dagli abissi più infetti del pianeta, cresciuta a scorie nucleari e disperazione umana, e la sua presenza è l'ultimo suono che sentirete. La sua conchiglia è un monumento alla corruzione atomica, il suo occhio verde e gigantesco pulsa di vita innaturale, e la sua perla vale più dell’intero PIL dell’Eurozona. A meno di trenta metri, inizierete a perdere i capelli e sanguinare dagli occhi, prima di dissolvervi in particelle subatomiche. Le sue emissioni sonore marine vi sussurreranno "Fottiti e torna indietro". Il desiderio che esaudisce? Quello di non averla mai cercata. Squish!
8	Scarabarman	Bilanciato	15	Cocktail ai metalli pesanti	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Tripla shakerata	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Alcolismo distruttivo	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Happy Hour tossico	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Vermouth radioattivo	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Shackeramento letale	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Hic! Burp! Glug glug! Nato da un amplesso blasfemo tra un cervo volante gigante e l'Uomo di Latta, Scarabarman è il barman definitivo, e la vostra condanna. Con braccia meccaniche che vorticano shakers incandescenti e un alito di gin e ruggine che mi fa hic sterminare una città, vi offrirà solo due uscite dal suo bar: ubriachi fradici o morti stecchiti. È un alcolista inveterato, e il suo "Sbronzo di Ferro", un mix di assenzio, olio motore e disperazione, è il suo capolavoro. L’ultima persona che ha provato a mandarlo indietro ha dichiarato di aver visto Dio. Hic!
9	Sborniadrago	Bilanciato	19	Respiro del drago ubriaco	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Pissing autoinflitto	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Bava alcolemica	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Etilofiamma ancestrale	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Volo barcollante	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Incendio digestivo	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Se vi imbatterete nello Sborniadrago, fate attenzione a come gli offrite da bere, perché è un dannato snob che sbava mentre parla e vi farà errori di pronuncia. La leggenda narra che la caduta dell’Impero Romano fu colpa sua, non dei barbari, per un bicchiere pulito. Non accetta drink senza guarnizione, e se gli date il gin senza ghiaccio, il vostro destino è segnato. Il suo fiato è un Negroni bollente a centoventi gradi, e dopo il settimo gin tonic, la sua tolleranza alcolica è inesistente, diventando ancora più pericoloso. Preparatevi a farvi insultare la madre.
10	Tigrallo	Bilanciato	19	Ruggito neoborbonico	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Morso neomelodico	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Chiagn e fott	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Fasti neobarocchi	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Digestione della bufala	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Confusione genetica	Danno: Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Aoh, se incrociate il Tigrallo alla Reggia di Caserta, preparatevi a un'operazione di rimozione coatta di interiora. Questo mostro geneticamente assurdo, incrocio tra tigre e zebrallo, si aggira tra gli stucchi barocchi con un accento campano che vi sbrana l’anima. Ha un’impercettibile puzza di stalla, e fa strage di turisti colpevoli di aver pronunciato "andiamo a Napoli" senza specificare che Caserta è una provincia a sé. Non corre, sfreccia. Non azzanna, ma esegue una vivisezione con tempistiche da cronometrista olimpionico.
11	Roboraffa	Bilanciato	16	Ossiconi Assassini	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Allungamento	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Morso erbivoro metallico	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Coccolone letale	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Bioingegneria pansessuale	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ricordo della savana	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Se vedete Roboraffa avanzare, inginocchiatevi o correte, figgiêu. Nata da esperimenti di bioingegneria spinti troppo in là da furry ubriachi, questa giraffa fusa con una macchina da guerra è una torre d’avorio con armi a impulsi e una resistenza emotiva discutibile. È potentissima, ma iper-sensibile: insultate la sua altezza e potrebbe distruggervi una città con una raffica di missili al napalm. E la cosa più inquietante? Ha una dotazione biologica femminile completamente funzionante.
12	Florona	Erbaceo	16	Seduzione furry	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Bouquet di dildi	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Aroma inebriante	Danno: 5	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Leccata di gatta	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Coccolone peloso	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Dildo a sorpresa	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Se il suo sguardo vi ipnotizza e la sua chioma ondeggia, sappiate che Florona è una cazzo di entità primordiale del polline e della disperazione, e vi parlerà sempre come se fosse triste. Era un’adorabile gatta floreale, sogno umido di ogni furry, ma ora, appena vi avvicinate, inizia l’agonia. Ogni primavera causa più vittime dell’asma che dell’influenza, semplicemente stando lì, bellissima, elegante. Se provate a potare la sua maestà floreale, vi seppellirà in un’orgia di edera assassina e polline più letale dell'antrace.
13	Ran-occhio	Erbaceo	15	Sputo del Gange	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Finocchiata	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Spruzzo di girini	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Sovrappopolazione	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Germoglio letale	Danno: 4	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Aromaterapia estrema	Danno: Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Se Ran-Occhio vi vede con un panino col prosciutto, siete già morti. Emerso dalle acque infette del Gange come un'incarnazione anfibia della vendetta vegetale, questo crociato del veganismo militante ha un accento marchigiano inconfondibile. È un coltivatore ossessivo di finocchi, e chiunque osi mettere in dubbio la qualità della sua merce viene sommerso da insulti, verdure e un colpo secco di radicchio in piena faccia. L'unico modo per sopravvivere al suo sguardo di disprezzo? Gridare: “Lunga vita alla dieta plant-based!” e offrirgli un gin tonic con semi di finocchio.
14	Arundizilla	Erbaceo	20	Amore non corrisposto	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Conquista vegetale	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Nuggets vegani	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Lancia di sedano	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Crociata crudista	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Zuppa di umani	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Rutt! Quando vostra nonna vi diceva “Parla con le piante, che ti ascoltano”, non intendeva Arundizilla. Questa è il risultato di un esperimento scientifico finito malissimo: un incrocio tra bambù geneticamente modificato, un giardiniere con un pollice troppo verde e il puro e incontaminato terrore cosmico. Cresce incontrollata, divora tutto, e soprattutto non si può potare. Se la mettete al sole, vi colonizzerà il pianeta in due ore. È una vegetariana carnivora, ma solo "per principio". Rutt! Ogni tentativo di tagliarla la fa ricrescere più incazzata, costringendovi a conviverci, come un coinquilino tossico.
15	Gelsosauro	Erbaceo	17	Tirannomorso	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Pissing dalla pelle	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Odio aromatico preistorico	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Urina corrosiva	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fioritura esplosiva	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Petalo terminale	Danno: Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Ammazza, se vi trovate di fronte a Gelsosauro, sappiate che state guardando un Tyrannosaurus Rex mutato dai pollini e dall'invasività dei gelsomini, con un rutto de decomposizione che vi devasta l'anima. Nato da uno scienziato pazzo che non aveva previsto il dettaglio floreale, è un abominio di zanne e fiori. Non fatevi ingannare dalla sua fragranza delicata: espelle urina direttamente dai pistilli sul corpo, un getto caldo e corrosivo che vi lascerà campi sterili e traumi permanenti. Consuma venticinque chili di carne al giorno, riducendo le sue vittime in brandelli. E per il resto, caga normalmente.
16	Lavandasma	Erbaceo	17	Furto dell'anima	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Incubo alla lavanda	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Abbraccio di marsiglia	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Profumo letale	Danno: 2	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Essenza di morte	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Incubo profumato	Danno: Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Se Lavandasma vi appare, il suo tono un po' depresso vi avvolgerà in un'aura di malinconia. È lo spirito di una persona morta in un campo di lavanda, e la sua unica missione è mangiarvi l'anima. Ma non temete troppo, perché vi lascerà un gradevole aroma nella tomba. È l'unica cosa che le riesce bene, in fondo. Non potete scappare, è solo il suo modo per farvi sentire un po' meglio, forse, nel vostro eterno riposo profumato.
17	Salviananda	Erbaceo	17	Colpo femminista	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Colpo ecologista	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Incatenata all'opera d'arte	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Eco-terrorismo letale	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Liana strangolatrice	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Ascia verde sangue	Danno: Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Se incontrate Salviananda, sappiate che non è qui per le vostre petizioni cringe, bro. Lei agisce, e con lo slang della Gen Z vi farà capire che il cambiamento climatico lo ferma una testa mozzata nel bidone dell’umido, non la raccolta differenziata. Le emissioni di CO₂? Si compensano con SUV in fiamme e fabbriche che esplodono. Se avete mai detto "eh ma servono soluzioni realistiche", preparatevi a diventare concime per la sua nuova foresta. Chi produce più CO₂ di una pianta di basilico, la troverà dietro l'angolo con l'accetta.
18	Koajhonny	Erbaceo	21	Bicipite balsamico	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Caduta dall'albero	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Potenza officinale	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Abbraccio asfissiante	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Marsupio esplosivo	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fisting marsupiale	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Dall’esterno, Koajhonny vi sembrerà il sogno proibito di una casalinga annoiata: pettorali cesellati, barba da taglialegna e uno sguardo che promette avventure. Ma non fatevi ingannare: sotto quella tuta ipertecnologica da macho alpha, si nasconde un koala assassino con l’ormone in perenne ebollizione. Creato in laboratorio per infiltrarsi e sedurre gli umani fingendo di essere umano, il suo appetito sessuale è pari a quello di un riccio in stagione degli amori. Se non è impegnato a scalare alberi di eucalipto, lo troverete a letto con qualcuno che non avrà mai più una vita normale.
19	Rosiro	Erbaceo	18	Sguardo irresistibile	Danno: 3	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Petali di rosa	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Orgoglio Queer	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Parata orgiastica	Danno: 2	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Corteo bestiale	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Fluido ipnotico	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Tesoro, se Rosiro vi abbraccia, preparatevi a un'esperienza mistica che vi farà rivalutare ogni certezza, perché questo tapiro sinuoso con una carica erotica da mandria in calore vi parlerà come una checca disinibita. Le sue strisce ipnotiche e i suoi occhi magnetici sono armi letali. Eterosessuali convinti? Mai esistiti, dopo una notte con Rosiro vi ritroverete con un Negroni in mano e un ventaglio di piume, chiedendovi cosa sia successo. Non è solo libidine sfrenata, è un filosofo, un rivoluzionario, un'icona vivente del desiderio senza etichette.
20	Rosella	Erbaceo	16	Shock pettoruto	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Rose transfemministe	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Penetrazione a sorpresa	Danno: 3	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Orgia infernale	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Stregoneria sodomita	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Quartetto letale (seno e gonadi)	Danno: Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Se incrociate Rosella, sappiate che il suo vocione da uomo grosso vi farà vibrare le viscere, mentre i suoi occhi rossi brillano di una malizia sboccata. Nata da un'antica, maledetta perversione che ha preso forma tra le luci di un luna park infernale, questa creatura demoniaca con corna e ali vi avvolgerà in un'aura di peccato puro, con rose di carne che sbocciano sulla sua pelle screpolata. La sua essenza è la lussuria contorta, capace di corrompere con una grazia che vi farà implorare di annegare nei vostri vizi. Lasciatevi sedurre dal suo canto profondo e dal suo sguardo che promette abissi di piacere e perdizione.
21	Cybermint	Erbaceo	14	Sensualità cibernetica	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Vagina con firewall	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Turbine mentolato	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Upload estremo	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Mentolo assassino	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Sistema di difesa attiva	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Se incontrate Cybermint, sappiate che state assistendo all'evoluzione tramite sviluppo AI di un Roomba da serra intensiva. Lei vi parlerà come un'assistente virtuale anni 2000, e il suo corpo cibernetico, con le sue ramificazioni elettroniche luminose, nasconde una peculiarità anatomica: una vagina piperita. È stata creata per ottimizzare la coltivazione della menta, e il suo interfacciamento sensoriale è progettato per un'esperienza... rinfrescante. Preparatevi a un'interazione sensoriale che vi farà rivalutare ogni concezione di piacere organico.
22	Rosmaruma	Erbaceo	17	Saggezza aromatica	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Scorza impenetrabile	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Stoico condimento	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Letame sepolcrale	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Defecazione distruttiva	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Radice strangolatrice	Danno: Danno: 3	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Se vi addormentate accanto a Rosmaruma, il suo pensiero vi pervaderà: "Io sono la pace, l'immobilità, il profumo che ti culla." Questo imponente mostro muschioso, con occhi blu cielo e corna di pino, è la statua sacra del relax, ma anche il motore di una digestione esplosiva. Emette dodici chili di materia organica al giorno, fertilizzando la terra con una potenza tale che la scienza ha smesso di interrogarlo sulla sua origine. Voi sperimenterete i sogni più sereni, ma chi resta troppo a lungo... diventerà la sua prossima foresta.
23	Cetriolana ottava	Erbaceo	16	Regalità falliforme	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Cetrioli birichini	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Sudditanza ortaggifera	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Incastro imperiale	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Punizione alla plebaglia	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Entra tutto signori	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Seduta sul suo trono di ortaggi fallici, Cetriolana Ottava è la regina indiscussa del regno dei cetrioli, e il suo corpo è un mistero anatomico. Adornata di gioielli verde smeraldo, la sua carne è una cattedrale dell'accoglienza ortofrutticola, capace di ospitare fino a quindici cetrioli contemporaneamente. I cortigiani sussurrano che il suo harem vegetale non sia un vezzo, ma una fonte di energia mistica che le conferisce il dominio assoluto su chiunque incroci il suo sguardo lascivo. Chiunque osi sfidarla verrà immediatamente trasformato in un umile cetriolino, destinato a unirsi alla sua sacra, umiliante collezione.
24	Rosmanguilla	Erbaceo	16	Pesce condito	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Amore interraziale	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Secrezioni anguillose sguillose	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Scivolata mortale	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Scarica elettrica	Danno: 3	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Morso viscido ma saporito	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Sssss... Se il concetto di food porn avesse una forma biologica, sarebbe Rosmanguilla, la vostra personale emulsione gourmet che sibila quando parla. Nata già aromatizzata con rosmarino e limone, e con una forma fallica imbarazzante, è convinta di essere una leggenda sacra che protegge il mondo dall'insipidezza assoluta. Se vi avvicinate con una padella, emette un sibilo di disprezzo e vi lascia addosso un retrogusto di rimpianto. Non tenta di sfuggire alla forchetta; aspetta solo di essere degnamente accompagnata da un vino decente. Sssss... E fidatevi, non si fa andar bene il primo bianco che trovate.
25	Banona	Fruttato	17	Ti plano nel culo con una banana	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Banana split	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Volo Chiquita	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Doppio selfie letale	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Like assassini	Danno: 1	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Followers della morte	Danno: Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Se credete che Banona possa essere vostra amica, siete dei fottuti illusi. Lei non lo è mai stata, e non lo sarà mai, nemmeno a pagamento, con quella sua volgarità innata che vi schiaccia. Affiancata dal suo fido Bananodemonio, una creatura a metà tra una banana marcia e l’incubo erotico di un fruttivendolo maledetto, si aggira nelle ombre del regno oscuro, spezzando sogni con un ghigno di pura indifferenza. Se osate anche solo pensare di meritare il suo tempo, preparatevi a un’umiliazione tale da farvi rivalutare ogni vostra interazione sociale passata.
26	Tony Ephedrina	Fruttato	16	Amore per le droghe	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Trip in the Bag	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Cristalloni volanti	Danno: 5	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Euro messi male	Danno: 5	Spogliato - Non può difendersi al prossimo attacco.	Tachicardia demoniaca	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Morte da after	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Fratellì, se incontrate Tony Ephedrina, vi sparerà addosso le sue teorie sulla psiconautica urbana con la voce di un bambino drogato. Questo essere, che Madre Natura avrebbe creato sotto anfetamine per settantadue ore consecutive, è l'icona vivente della psiconautica urbana. Le sue vene scorrono a metà tra linfa ed MDMA, e i suoi capelli erbosi, a crescita autonoma, assorbono qualsiasi sostanza chimica presente nell'aria. È convinto che il 5G stia leggendo i suoi pensieri e ogni cartellone pubblicitario lo stia spiando.
27	Cervarancio	Fruttato	17	Cazzo agrumato gargantuesco	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Buccia repellente	Danno: 4	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Cervopotenza ancestrale	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Esplosione di polpa	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Spremuta di muscoli	Danno: 3	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Corna cazzutissime del dio aranciato	Danno: Danno: 3	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Onde cerebrali: Io sono Cervarancio, l'abominio araldico nato dall'unione sacrilega tra un cervo e un'arancia sanguigna mutante, frutto di esperimenti geneticamente irresponsabili e di una spremuta infernale. I suoi occhi incandescenti scrutano l’anima degli stolti che osano avvicinarsi, mentre le sue corna, cariche di agrumi esplosivi, vibrano di elettricità statica. Le sue zampe spezzano la terra rilasciando un'essenza agrumata tanto inebriante quanto tossica. Se osate assaporare una delle sue fette, la vostra lingua si dissolverà in un mix di fuoco e succo citrico, ma i superstiti giurano che il sapore fosse comunque migliore del vostro solito gin tonic con limone del bar sotto casa.
28	Merlotta	Fruttato	14	Aratro voltaorecchio	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Cultivar franche di piede	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Lieviti indigeni	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fermentazione estrema	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Vinificazione crudele	Danno: 5	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Tannino letale	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Se incontrate Merlotta, vi troverete di fronte a un monumento all'arte dell'autodistruzione enoica, che vi parlerà con accento toscano tra un sorso e l'altro. La sua tenuta di quattrocento ettari è una dispensatrice di sbronze a ciclo continuo, ma esclusivamente per il suo personale consumo. Dicono si scoli la prima barrique prima dell'alba. Se le chiedete un bicchiere, vi allungherà il tubo dal suo tank da venti ettolitri, guardandovi con compatimento per il vostro ridicolo tentativo di bere con moderazione. Se vi trovate senza bicchiere in mano, tra i suoi filari, siete voi quello fuori posto.
29	Corvananas	Fruttato	18	Seme profumato	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	6Danno: 19 senza l'one	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Wrestlermania 18	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Scatto tropicale	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Becco afrodisiaco	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Volo acrobatico	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Madamin, se vi trovate davanti a Corvananas, sappiate che è nato da un tragico esperimento culinario avvenuto in un bordello caraibico, e vi parlerà con quel suo accento piemontese da seduttore dannato. Questa chimera muscolosa di piume nere e polpa gialla è pronta a farvi volare nel paradiso del piacere o dell’agonia. Il suo corpo, ricoperto da una corazza di ananas ruvidissima, è perfetto per sessioni di massaggi esfolianti estremi. La sua presa aerea, il suo "Pineapple Express", vi ricopre di succo d'ananas che vi ammorbidisce la carne e vi lascia un retrogusto tropicale nelle zone erogene, creando una dipendenza che durerà almeno quarantotto ore.
30	Fiammaciofo	Fruttato	18	Incubo fiammeggiante	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Odore di carciofo	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Multimasturbazione poli bukkakika	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Fiamma tossica	Danno: 2	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Cuore di piombo	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Carbonizzazione finale	Danno: Danno: 1	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Aoh, se vi imbattete in Fiammaciofo, sentirete che è un semplice carciofo nato nella Terra dei Fuochi, ma ha acquisito caratteristiche che nessun vegetale dovrebbe mai avere: irradia calore, brilla al buio e se lo toccate troppo a lungo, potreste sviluppare un terzo capezzolo. Con il suo accento molisano, vi dirà che non è un presidio Slow Food… ancora, ma sta corrompendo i commissari con sapori unici e un leggero retrogusto di roghi tossici. La sua carne è tenerissima, ma chi lo mangia riferisce sensazioni contrastanti tra l'estasi gastronomica e l'improvvisa voglia di fare una TAC di controllo.
31	Rosa cagnolina	Fruttato	15	Marmellata di rosa canina	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Gender gap vegetale	Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Spine dell'amore sopra ogni cosa	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Allattamento tossico	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Morso avvelenato	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Latrato fatale	Danno: Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Quando la natura si è rotta il cazzo della cementificazione, ha partorito Rosa Cagnolina, la materializzazione della sua ira botanica. Nata dalla pazienza millenaria, è un incrocio tra una driade incazzata e un cespuglio infestante, con occhi che brillano di rancore fotosintetico. Non si limita a far germogliare la vita: la usa per soffocarvi lentamente mentre vi sussurra i nomi scientifici delle piante velenose. I suoi seni, scandalosamente perfetti, producono bacche allucinogene che causano visioni di un mondo senza plastica, un orrore per chi vive di fast food. Se la incontrate, il suo strillo silenzioso vi darà una scelta: o diventate vegani, o diventerete fertilizzante.
32	Pipimone	Fruttato	17	Aspra trascendenza	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Diaconato agrumato	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Ultrasuoni sacri	Danno: 4	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Minzione divina	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Getto purificatore	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Lavaggio estremo	Danno: Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	A-iò, se vi trovate davanti al Pipimone, sappiate che è maestoso, divino, ma palesemente sbagliato. Questo ibrido nato dal matrimonio nefasto tra l’eleganza di un gufo dorato e la sfiga genetica di avere un limone al posto dello scroto, spruzza succo citrico in aria ogni volta che sbatte le ali. Durante la stagione degli amori, l'aria si riempie di un aroma acidulo che fa correre ai ripari persino i monaci dei templi sacri. Berreste davvero una limonata, sapendo che potrebbe contenere l'essenza delle sue gonadi divine?
33	Eremillo	Fruttato	19	Saggezza antica	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra. - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Un sacco di bacche	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	GDILF	Danno: 2	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	vita senza defecazione	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Antiossidante pazzesco	Danno: 2	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Respiro ai mirtilli	Danno: Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Se incontrate Eremillo, sappiate che vaga per le montagne più remote da oltre due secoli, nutrendosi solo di mirtilli e ignorando completamente l’esistenza della civiltà umana. Il suo corpo, tempio di purezza e potenza, è forgiato dal gelo e da un’alimentazione così ricca di antiossidanti che il tempo stesso ha smesso di intaccarlo. Non invecchia, non si ammala, non si sporca. Il suo profumo naturale di mirtilli vi avvolgerà, ma attenzione: non ha mai visto una donna in vita sua, e il primo che prova a spiegargli cosa sia il sesso rischia di essere disintegrato con una sola, breve e devastante occhiata confusa.
34	Mangodillo	Fruttato	19	Jackpot	Danno: 3	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Una rondine andata via	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Ludopatia tropicale	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Scaglie da poker	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	All in fruttato	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Slot machine vertebrale	Danno: Danno: 2	Spogliato - Non può difendersi al prossimo attacco.	Se incrociate Mangodillo, lui vi canterà la sua triste storia di superstar. "Ooooh, io ero la suuuuperstar, la voce più seducente e tropicale che il mondo animale avesse mai conosciuto!" Ma poi, ahimè, sono arrivati i casinò. Le luci delle slot machine lo hanno risucchiato nel tunnel della ludopatia. L’unico frutto che lo interessa non è più il mango, ma quello maledetto dell’azzardo. Ora non canta più, ma gioca senza sosta, sperando che la prossima giocata gli restituisca tutto quello che ha perso, mentre la figlia, poverina, prova a riavviare la dinastia.
35	Lampolpo	Fruttato	18	Amore tentacolare	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ventose succhiatrici	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	o' Purp 'mbuttunat	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Ventosa soffocante	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Stretta mortale	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Calamaro stritolante	Danno: Danno: 2	Spogliato - Non può difendersi al prossimo attacco.	Diciamocelo chiaro: Lampolpo è il risultato del delirio collettivo di uno chef troppo ambizioso e di un produttore di film giapponesi con gusti discutibili, e vi parlerà con l'accento abruzzese di una zia incazzata. A metà tra un polpo da carpaccio e una macedonia maledetta, questa creatura non sa se vuole essere mangiata o solo guardata con orrore. La sua acidità dei frutti rossi gli ha conferito un’espressione perennemente incazzata. Il suo curriculum nel cinema giapponese è lungo quanto un suo tentacolo, con apparizioni in film vietati ai minori e nei peggiori hentai di nicchia. Il suo inchiostro è afrodisiaco, e chi lo inghiotte prova una strana combinazione di estasi e pentimento immediato.
36	Delfimaru	Fruttato	17	Shuriken delfinici	Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Sfintere ninja	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Voglio diventare Hokage	Danno: 2	Spogliato - Non può difendersi al prossimo attacco.	Onda assassina	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Lama marina	Danno: 4	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Nuotata kamikaze	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Se vi imbatterete in Delfimaru, sappiate che non è un cazzo di delfino, ma un incubo ninja addestrato nelle arti del ninjutsu e nella pura, fredda brutalità, e la sua volgarità è nell'efficienza letale dei suoi colpi. Nato nel cuore del Villaggio delle Arance, si muove tra le onde senza fare rumore, colpendo prima che la vittima possa capire cosa stia succedendo. Le sue pinne sono lame affilate, i suoi occhi due fottuti rubini assetati di sangue. Il suo villaggio lo ha cresciuto nel culto dell’arancia, la sacra fonte di vitamina C e distruzione, e ora ogni fetta d’arancia che vedrete è probabilmente l’ultima cosa che vedrete nella vostra vita.
37	Pignacano	Fruttato	18	Pinoli volanti	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Piume ignifughe	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Beccata di tristezza	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Seme velenoso	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Radice esplosiva	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Partenogenesi letale	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Se vi trovate davanti a Pignacano, lui vi guarderà con i suoi occhi tristi e vi sputerà un pinolo in faccia, imprecando con le sue tante parolacce. Questo tragico volatile, metà tucano maledetto e metà scultura di corteccia infestata, non ha organi sessuali e non capisce il piacere fisico. Per riprodursi, deve ingoiare compulsivamente coni di pino e poi sputare pinoli con una precisione da cecchino. Le sue piume sono fatte di squame di legno e dal suo becco trasuda miele, perché l’universo ha deciso di renderlo ancora più disturbante.
38	Pompecora	Fruttato	19	Aspra lana	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Sbucciare un esperidio	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Pom-pecorina	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Tosatura selvaggia	Danno: 2	Spogliato - Non può difendersi al prossimo attacco.	Rutto alcolico	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Zoccolo frantumatore	Danno: Danno: 3	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Hic! Burp! Se incontrate Pompecora, lei vi fisserà con occhi che bruciano come la vostra esofagite dopo un succo d'arancia a stomaco vuoto, e vi parlerà come un ubriaco. Lei è la prova vivente che il consumo eccessivo di pompelmo porta alla follia mistica. Le sue giornate passano tra spremiture compulsive, strani rituali alcolici e occasionali sacrifici agli dèi del fermentato artigianale. Il suo "vero" vino di pompelmo va affinato con ossa umane, lacrime di astemi e una bestemmia detta sottovoce. Con la sua "Spremitura Eruttiva", vi sputerà in faccia un getto di succo acido, infliggendovi nausea permanente e la riduzione del 50% della vostra dignità.
39	Winenot?	Fruttato	16	Sensualità furry	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Molti bicchieri di vino	Danno: 4	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Potenza radical chic	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Sorso letale	Danno: 3	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Sciabolata da gigolò	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Sbronza assassina	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Chèwie, se Winenot vi seduce con il suo lessico forbito, sappiate che è un gigolò trasformato in un pedante connoisseur di vini naturali, che vi parla con la r moscia. Un tempo banale sciupafemmine da salotto, ha scoperto i vini naturali e da allora non parla d'altro. Ogni conversazione si trasforma in un monologo sull'importanza della fermentazione spontanea e sulla superiorità morale del biodinamico, bombardandovi con nomi di viticoltori sloveni mai sentiti. Il suo fascino è inspiegabile, un mix letale tra pelo folto, cultura e sguardo da “so di essere meglio di te” che lo rende irresistibile per chiunque abbia un minimo di autostima da mettere in discussione.
40	Callista	Speziato	17	Necrofilia indotta	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Ritorno dalla morte	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Putrefazione avanzata	Danno: 4	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Cripto-overdose	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Borsa dritta al cimitero	Danno: 4	Spogliato - Non può difendersi al prossimo attacco.	Morte NFT	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Se incontrate Callista, sappiate che un tempo era un'anima pura e solare, raggiante di speranza e positività. Amava i tramonti, le tisane e credeva nell’umanità. Poi ha scoperto le criptovalute. Ora, la sua anima è corrotta oltre ogni possibilità di redenzione, e la sua allegria è maniacale. Non parla d'altro che di NFT, token e rendite passive, e chiunque osi guardarla negli occhi viene ipnotizzato in un vortice di investimenti che non porteranno mai a nulla. La sua voce è un sussurro malevolo che riecheggia nella notte: "Ehi fratello, vuoi guadagnare senza fare un cazzo?", e se rispondete sì, siete fottuti.
41	Cannellorca	Speziato	20	Affondanavi speziato	Danno: 4	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Colpo idrofobo	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Grasso che cola	Danno: 2	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Tsunami alla cannella	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Ondata Macellatrice	Danno: 2	Spingi l’avversario di 2 caselle nella direzione dell'attacco. Se sbatte contro una parete, perde 1 PV. Se finisce contro un altro ginocchio, entrambi perdono 1 PV.	Fauci del giovedì	Danno: Danno: 1	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Se sentite il rombo di Cannellorca, preparatevi, perché è il Leviatano Speziato, il flagello dei mari, e la sua minaccia è chiara: "il mare è mio, e a lui va reso tributo". Non è il cazzo di Willy che salta gli scogli, ma un demone delle profondità, sempre cattivo e minaccioso. Ovunque passi, l’oceano si colma di una scia mortifera di sangue e cannella, il vostro ultimo respiro. Le sue fauci grondanti non si chiudono mai senza strappare carne, e le onde si tingono di un rosso speziato. La sua unica debolezza è la cioccolata: un odore di fondente la placa un istante, prima di tornare a macellare ogni cosa a vista.
42	Anicinzia	Speziato	18	Magia del Rasentin	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Follia dei ghiacci	Danno: 4	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Arcanomanzia balsamica	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Ghiacciolo letale	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Infusione stregata	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Sbornia dolce	Danno: Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Anicinzia, la maga veneta e ubriaca, vi fissa con un sorriso inquietante, il bastone d'anice in pugno. Lei è una dannata leggenda che ha trovato la vera fonte del potere nell’anice, ingurgitando così tante bottiglie di pastis e sambuca che il suo corpo è ormai una distilleria ambulante. Il suo sangue è una soluzione alcolica al settanta percento, e il suo respiro potrebbe infiammare un caminetto spento. Se provate a offrirle un drink che non sappia di anisetta e morte, vi guarderà con disprezzo e, senza dire una parola, trasformerà il vostro cocktail in un intruglio a base di anice. I villaggi devastati dopo il suo passaggio sono la prova che Anicinzia non beve mai da sola.
43	Fumello	Speziato	17	Ganja power	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Cartina aromatica	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Stonamento	Danno: 3	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Bomba spliff	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Teoria del complotto	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Abduction aliena	Danno: Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	NAh, mi bredren, se incontrate Fumello, lui è l'incarnazione vivente dello "stay irie", e vi parlerà come un rastafariano. Un'anima che vibra con le onde della natura, un mistico del verde che ha elevato il concetto di "one love" a un livello ultraterreno. Il tempo per lui è un'illusione imposta da Babylon, e il mondo si divide tra chi sa rollare bene e chi deve ancora illuminarsi. "Roll pon di fire, but neva pon di liar" è la sua regola. Chi porta vibrazioni negative nella sua giungla rischia di finire avvolto in una nuvola da cui non si sveglia più.
44	Peperonbro	Speziato	18	Malavita piccante	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Thug life	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Battaglia rap	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Street food killer	Danno: 4	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Salsa esplosiva	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Capo gang aromatica	Danno: Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	"Oh BRO, senti come picca!", vi dirà Peperonbro, il boss delle scoville, con lo slang dei ragazzi di strada e un'aria da king sopra la sua auto sportiva. Non è un cazzo di peperoncino qualunque, ma il terrore che fa sudare anche i più duri. Leccare una delle sue dita equivale a un viaggio mistico in terapia intensiva, perché lui fuma sigarette arrotolate con le lacrime di quelli che hanno provato a mangiarlo. Se vi tocca, il vostro stomaco entra direttamente nel Programma Protezione Testimoni, perché nessuno sopravvive per raccontarlo senza perdere almeno due organi.
45	Blobaffè	Speziato	19	Caffè sospeso	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Scordammc' o passat	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Tazzulella	Danno: 3	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Espresso bollente	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Crema di fango	Danno: 2	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Tazzina mortale	Danno: Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Ué, se Blobaffè vi si para davanti, sappiate che è il flagello liquido che infesta il Golfo di Napoli, nato dall’eccesso di generosità partenopea e da un’infinita sequela di caffè sospesi mai reclamati. Questa aberrazione torbida sprigiona vapori infernali di tostatura e condanna i miseri a un’agonia di veglia perpetua. Non vi uccide col ferro né col fuoco: vi desta, vi scuote, vi esige vigili oltre i confini della follia, finché il cuore non cede e le vene si induriscono come la crosta di una tazzina. Nelle notti di scirocco sentirete sussurri aromatici risalire dal golfo: "Vulit o' cafè?", bisbiglia, con voce soave e letale.
46	Speziatopo	Speziato	19	Spaccio di pepi	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	La rogna	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Orecchie da mercante	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Dose letale	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Formaggio drogato	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Topo kamikaze	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Priviet! Se incontrate Speziatopo, il re della polvere fine e l’alchimista di quartiere, con la sua voce russa vi proporrà un pizzico di pepe di Sichuan che vi paralizzerà la lingua. Le sue operazioni sono furtive e precise, si muove tra i vicoli del mercato con la rapidità di una leggenda vivente. Non vende solo spezie, брат, vende esperienze: roba che quando la mettete sulla lingua vedete la Madonna in trip di paprika. Se le cose si mettono male, Puff! Scompare in una nube di polvere di cumino e riappare al prossimo angolo, pronto a servire il prossimo cliente con un sorriso da roditore e una bustina di pepe lungo che vi farà sognare l’aldilà.
47	Borghesiglio	Speziato	18	Opulenza polentona	Danno: 3	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Fascino alla moda	Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Riproduzione come conigli	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Scacco matto massonico	Danno: 4	Sorso salvifico - Se il tuo bicchiere contiene più gin tonic rispetto a quello dell’avversario, puoi bere un sorso e recuperare 2 Punti Vita.	Bonifico istantaneo	Danno: 3	Succhiaggio PV - Recuperi PV pari al danno che infliggi.	Martiny dry a  25€	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Oh, bel, se incontrate Borghesiglio, sappiate che lui è il re indiscusso della sboronata elegante, nato e cresciuto ad Arcore, e vi parlerà con il suo accento milanese impeccabile. Con la sua giacca steampunk sartoriale e il monòculo d’oro, vi squadrerà con quell’aria da sciur che vi fa sentire un povero tapino. Se siete convinti che una cena all-you-can-eat sia lusso, lui vi riderà in faccia, tra un sorso di gin botanico e un affare con qualche industriale lombardo. Il suo NFT è in dialetto meneghino, e accetta solo bonifici istantanei.
48	Teabear	Speziato	18	Zanna della teina dopante	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Tazza di the sanguinoso	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Ruggito dell'orso mangiabambini	Danno: 2	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Porcellana avvelenata	Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Filtrino strangolatore	Danno: 2	Blocca attacco - Il bersaglio non può attaccare al prossimo turno.	Infusione letale	Danno: Danno: 2	Ammosciamento - L’avversario fa massimo 1 danno al prossimo attacco.	Se vi avventurate in Siberia, il pericolo più grande non è il gelo, ma Teabear, un orso assassino che si crede un intellettuale. Vi parlerà con il suo accento balcanico, spiegandovi che, dopo aver imparato il galateo britannico squartando un campeggiatore, non uccide senza prima aver sorseggiato una tazza di Earl Grey. Le sue regole sono ferree: mai saltare l’infuso delle cinque, mai mettere lo zucchero nel tè – perché lo zucchero è da pezzenti, il sangue fresco è più bilanciato – e mai farlo incazzare. L’ultima persona che ci ha provato è stata versata nella tazzina.
49	Tzatzikeye	Speziato	20	Dressing assassino	Danno: 4	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Muffa cetriolifera	Danno: 4	Alcolismo competitivo - Se il tuo bicchiere contiene meno gin tonic rispetto a quello dell’avversario, infliggi +2 danni.	Insalata greca	Danno: 2	Cura - Recuperi 2 Punti Vita. Non puoi superare i PV massimi.	Diarrea esplosiva	Danno: 3	Inverti casella - I bonus della casella diventano malus per l’avversario finché ci resta sopra.	Emorroidi galattiche	Danno: 2	Paralisi totale -Il Ginocchio colpito non può muoversi né attaccare al prossimo turno (non cumulabile)	Vinaigrette mortale	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Se vi trovate davanti a TzatzikEye, sappiate che è una salsa tzatziki fresca, dimenticata nel frigo del vostro peggior incubo, e ora è qui per vendicarsi, in modo molto volgare. Evoluta in una divinità di disgusto e punizione che gli antichi greci avrebbero venerato, questa creatura con l'occhio fermentato vi guarda dentro l'anima e giudica ogni vostra scelta alimentare, specialmente se avete mai osato ordinare una pizza all'ananas, stronzi. Le sue muffe senzienti piangono siero lattico maledetto, e una sola goccia della sua essenza può maledire la vostra insalata greca, scatenando diarrea fulminante e crampi esistenziali. Il suo "Reflusso Olimpico" vi spruzzerà yogurt rancido in faccia, infliggendovi nausea permanente e la riduzione del cinquanta percento della vostra già scarsa dignità.
50	Fuega	Speziato	18	Piccantezza in straming	Danno: 4	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Orgoglio contadino	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	10000000000 Punti scorville	Danno: 3	Paura - Il bersaglio non può avvicinarsi a te nel prossimo turno, deve stare ad almeno 1 casella di distanza.	Dildo di fuoco	Danno: 3	Spogliato - Non può difendersi al prossimo attacco.	Tortura piccante	Danno: 5	Autolesionismo - Subisci 1 Pv di danno durante l'attacco	Onlyfans letale	Danno: Danno: 3	Danno sesso opposto - Se il giocatore avversario è di sesso diverso dal tuo, fai danno doppio.	Se i vostri occhi si posano su Fuega, sappiate che state guardando la divinità infuocata del capsicum, nata nelle segrete sperimentali di un laboratorio che produceva salse per OnlyFans. Lei, con la sua chioma ardente e gli occhi che bruciano di una malizia antica e sboccata, è la prova che il piccante può essere una maledizione divina. Ogni peperoncino che brandisce è una promessa di dolore sublime, un'estasi di sudore e bruciore che vi farà implorare pietà. La sua voce, roca e suadente, vi sussurra ricette infernali e segreti di coltivazione proibiti, mentre le sue fiale ribollono di alchemie che promettono di sciogliervi la lingua e l'anima. Preparatevi a pagare per il suo fuoco.
`;

// Function to parse the new raw text data
const parseAllGinocchiData = (rawData: string): { ginocchi: Ginocchio[], descriptions: Record<number, string> } => {
    const lines = rawData.trim().split('\n');
    const header = lines.shift(); // Remove header line
    if (!header) return { ginocchi: [], descriptions: {} };

    const parsedGinocchi: Ginocchio[] = [];
    const descriptionsMap: Record<number, string> = {};

    lines.forEach(line => {
        const parts = line.split('\t').map(part => part.trim());
        
        // Expecting 23 columns: ID, Nome, Tipologia, PV, (Attacco, Potenza, Effetto) x 6, Descrizione
        if (parts.length < 23) { 
            console.warn("Skipping malformed line (not enough columns):", line);
            return;
        }

        const id = parseInt(parts[0]);
        const nome = parts[1];
        const tipologiaStr = parts[2];
        const categoria = CATEGORY_MAP[tipologiaStr];
        const pvIniziali = parseInt(parts[3]);
        const descrizione = parts[22]; // 23rd column is index 22

        if (isNaN(id) || !nome || !categoria || isNaN(pvIniziali) || descrizione === undefined) {
            console.warn("Skipping line with missing or invalid critical data:", line, {id, nome, tipologiaStr, categoria, pvIniziali});
            return;
        }

        const attacchi: Attacco[] = [];
        for (let i = 0; i < 6; i++) {
            const attackName = parts[4 + i * 3];
            let attackDamage = parts[5 + i * 3];
            const attackEffect = parts[6 + i * 3];

            if (attackDamage) {
                if (attackDamage.startsWith("Danno: Danno: ")) {
                    attackDamage = "Danno: " + attackDamage.substring("Danno: Danno: ".length).trim();
                } else if (attackDamage.match(/^\d+$/)) { // If it's just a number like "4"
                    attackDamage = "Danno: " + attackDamage;
                }
                 // If it's already "Danno: X" or some other text, it's passed as is.
            } else {
                attackDamage = "Danno: N/A"; // Default for empty damage string
            }

            attacchi.push({
                dado: i + 1, // Dice face (1-6)
                nome: attackName || "Attacco Sconosciuto", // Default for empty name
                danno: attackDamage,
                effetto: attackEffect || "Nessun effetto speciale.", // Default for empty effect
            });
        }
        
        const folderName = CATEGORY_TO_FOLDER_NAME[categoria];
        if (!folderName) {
            console.warn(`Folder name not found for category: ${categoria} for Ginocchio ID ${id}. Defaulting image path.`);
        }

        parsedGinocchi.push({
            id,
            nome,
            categoria,
            pvIniziali,
            attacchi,
            colore: CATEGORY_COLORS[categoria],
            immagine: folderName ? `/images/Ginocchi/${folderName}/${id}.png` : `/images/placeholder.png`
        });
        descriptionsMap[id] = descrizione;
    });

    return { ginocchi: parsedGinocchi.sort((a,b) => a.id - b.id), descriptions: descriptionsMap };
};


const { ginocchi: ALL_PARSED_GINOCCHI, descriptions: PARSED_DESCRIPTIONS } = parseAllGinocchiData(RAW_GINOCCHI_DETAILS_TEXT);

export const ALL_GINOCCHI: Ginocchio[] = ALL_PARSED_GINOCCHI;
export const GINOCCHIO_DESCRIPTIONS: Record<number, string> = PARSED_DESCRIPTIONS;
